Momentum: momentum::SkeletonSolverFunctionT< T > Class Template Reference
momentum::SkeletonSolverFunctionT< T > Class Template Reference
#include <skeleton_solver_function.h>
Public Member Functions
SkeletonSolverFunctionT (const Character &character, const ParameterTransformT< T > &parameterTransform, std::span< const std::shared_ptr< SkeletonErrorFunctionT< T > > > errorFunctions={})
~SkeletonSolverFunctionT () override
double getError (const Eigen::VectorX< T > &parameters) final
double getGradient (const Eigen::VectorX< T > &parameters, Eigen::VectorX< T > &gradient) final
double getJacobian (const Eigen::VectorX< T > &parameters, Eigen::MatrixX< T > &jacobian, Eigen::VectorX< T > &residual, size_t &actualRows) final
double getJtJR (const Eigen::VectorX< T > &parameters, Eigen::MatrixX< T > &jtj, Eigen::VectorX< T > &jtr) override
double getSolverDerivatives (const Eigen::VectorX< T > &parameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad) override
void updateParameters (Eigen::VectorX< T > &parameters, const Eigen::VectorX< T > &delta) final
void setEnabledParameters (const ParameterSet &ps) final
Specifies which parameters should be optimized.
void addErrorFunction (std::shared_ptr< SkeletonErrorFunctionT< T > > solvable)
void clearErrorFunctions ()
const std::vector< std::shared_ptr< SkeletonErrorFunctionT< T > > > & getErrorFunctions () const
const Character & getCharacter () const
Provides access to the full character (replaces getSkeleton and getParameterTransform)
const Skeleton * getSkeleton () const
Legacy compatibility (delegates to character_.skeleton)
const ParameterTransformT< T > * getParameterTransform () const
Provides access to the parameter transform.
void updateMeshState (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state)
Updates mesh state if any error functions require it.
bool needsMeshState () const
Checks if any error functions require mesh state.
Public Member Functions inherited from momentum::SolverFunctionT< T >
virtual ~SolverFunctionT ()=default
virtual double getError (const VectorX< T > &parameters)=0
Evaluates the objective function at the given parameter values.
virtual double getGradient (const VectorX< T > &parameters, VectorX< T > &gradient)=0
Computes the gradient of the objective function.
virtual double getJacobian (const VectorX< T > &parameters, MatrixX< T > &jacobian, VectorX< T > &residual, size_t &actualRows)=0
Computes the Jacobian matrix for least squares problems.
virtual void getHessian (const VectorX< T > &parameters, MatrixX< T > &hessian)
Computes the Hessian matrix of second derivatives.
virtual double getJtJR (const VectorX< T > &parameters, MatrixX< T > &jtj, VectorX< T > &jtr)
Computes JᵀJ and JᵀR for Gauss-Newton optimization.
virtual double getJtJR_Sparse (const VectorX< T > &parameters, SparseMatrix< T > &jtj, VectorX< T > &jtr)
Computes sparse JᵀJ and JᵀR for large-scale problems.
virtual double getSolverDerivatives (const VectorX< T > &parameters, MatrixX< T > &hess, VectorX< T > &grad)
Computes derivatives needed by the solver.
virtual void updateParameters (VectorX< T > &parameters, const VectorX< T > &gradient)=0
Updates parameters using the computed step direction.
size_t getNumParameters () const
Returns the total number of parameters in the optimization problem.
size_t getActualParameters () const
Returns the number of parameters currently enabled for optimization.
virtual void storeHistory (std::unordered_map< std::string, MatrixX< T > > &history, size_t iteration, size_t maxIterations_)
Records solver state for debugging and analysis.
Additional Inherited Members
Protected Attributes inherited from momentum::SolverFunctionT< T >
size_t numParameters_ {}
Total number of parameters in the optimization problem.
size_t actualParameters_ {}
Number of parameters currently enabled for optimization.
Detailed Description
template<typename T>
class momentum::SkeletonSolverFunctionT< T >
Definition at line 21 of file skeleton_solver_function.h.
Constructor & Destructor Documentation
SkeletonSolverFunctionT()
template<typename T > momentum::SkeletonSolverFunctionT< T >::SkeletonSolverFunctionT (const Character & character, const ParameterTransformT< T > & parameterTransform, std::span< const std::shared_ptr< SkeletonErrorFunctionT< T > > > errorFunctions = {})
Definition at line 25 of file skeleton_solver_function.cpp.
References momentum::SolverFunctionT< T >::actualParameters_, momentum::SkeletonSolverFunctionT< T >::addErrorFunction(), momentum::SolverFunctionT< T >::numParameters_, and momentum::CharacterT< T >::skeleton.
~SkeletonSolverFunctionT()
template<typename T > momentum::SkeletonSolverFunctionT< T >::~SkeletonSolverFunctionT () override default
Member Function Documentation
addErrorFunction()
template<typename T > void momentum::SkeletonSolverFunctionT< T >::addErrorFunction (std::shared_ptr< SkeletonErrorFunctionT< T > > solvable)
Definition at line 332 of file skeleton_solver_function.cpp.
Referenced by momentum::SkeletonSolverFunctionT< T >::SkeletonSolverFunctionT().
clearErrorFunctions()
template<typename T > void momentum::SkeletonSolverFunctionT< T >::clearErrorFunctions ()
Definition at line 342 of file skeleton_solver_function.cpp.
getCharacter()
template<typename T > const Character & momentum::SkeletonSolverFunctionT< T >::getCharacter () const inline
Provides access to the full character (replaces getSkeleton and getParameterTransform)
Definition at line 60 of file skeleton_solver_function.h.
getError()
template<typename T > double momentum::SkeletonSolverFunctionT< T >::getError (const Eigen::VectorX< T > & parameters) final
Definition at line 64 of file skeleton_solver_function.cpp.
getErrorFunctions()
template<typename T > const std::vector< std::shared_ptr< SkeletonErrorFunctionT< T > > > & momentum::SkeletonSolverFunctionT< T >::getErrorFunctions () const
Definition at line 348 of file skeleton_solver_function.cpp.
getGradient()
template<typename T > double momentum::SkeletonSolverFunctionT< T >::getGradient (const Eigen::VectorX< T > & parameters, Eigen::VectorX< T > & gradient) final
Definition at line 86 of file skeleton_solver_function.cpp.
getJacobian()
template<typename T > double momentum::SkeletonSolverFunctionT< T >::getJacobian (const Eigen::VectorX< T > & parameters, Eigen::MatrixX< T > & jacobian, Eigen::VectorX< T > & residual, size_t & actualRows) final
Definition at line 134 of file skeleton_solver_function.cpp.
References momentum::getDimensions(), MT_PROFILE_EVENT, and MT_PROFILE_FUNCTION.
getJtJR()
template<typename T > double momentum::SkeletonSolverFunctionT< T >::getJtJR (const Eigen::VectorX< T > & parameters, Eigen::MatrixX< T > & jtj, Eigen::VectorX< T > & jtr) override
Definition at line 197 of file skeleton_solver_function.cpp.
References momentum::getDimensions(), MT_CHECK, MT_PROFILE_EVENT, and MT_PROFILE_FUNCTION.
getParameterTransform()
template<typename T > const ParameterTransformT< T > * momentum::SkeletonSolverFunctionT< T >::getParameterTransform () const inline
Provides access to the parameter transform.
Definition at line 70 of file skeleton_solver_function.h.
getSkeleton()
template<typename T > const Skeleton * momentum::SkeletonSolverFunctionT< T >::getSkeleton () const inline
Legacy compatibility (delegates to character_.skeleton)
Definition at line 65 of file skeleton_solver_function.h.
References momentum::CharacterT< T >::skeleton.
getSolverDerivatives()
template<typename T > double momentum::SkeletonSolverFunctionT< T >::getSolverDerivatives (const Eigen::VectorX< T > & parameters, Eigen::MatrixX< T > & hess, Eigen::VectorX< T > & grad) override
Definition at line 285 of file skeleton_solver_function.cpp.
References MT_PROFILE_EVENT, and MT_PROFILE_FUNCTION.
needsMeshState()
template<typename T > bool momentum::SkeletonSolverFunctionT< T >::needsMeshState () const
Checks if any error functions require mesh state.
Definition at line 353 of file skeleton_solver_function.cpp.
setEnabledParameters()
template<typename T > void momentum::SkeletonSolverFunctionT< T >::setEnabledParameters (const ParameterSet & parameterSet) final virtual
Specifies which parameters should be optimized.
Default implementation does nothing
Parameters
parameterSet Bitset where each bit indicates if the corresponding parameter is enabled
Reimplemented from momentum::SolverFunctionT< T >.
Definition at line 45 of file skeleton_solver_function.cpp.
updateMeshState()
template<typename T > void momentum::SkeletonSolverFunctionT< T >::updateMeshState (const ModelParametersT< T > & parameters, const SkeletonStateT< T > & state)
Updates mesh state if any error functions require it.
Definition at line 358 of file skeleton_solver_function.cpp.
updateParameters()
template<typename T > void momentum::SkeletonSolverFunctionT< T >::updateParameters (Eigen::VectorX< T > & parameters, const Eigen::VectorX< T > & delta) final
Definition at line 323 of file skeleton_solver_function.cpp.
References MT_CHECK.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/skeleton_solver_function.h
character_solver/skeleton_solver_function.cpp