Momentum: momentum::PosePriorErrorFunctionT< T > Class Template Reference
momentum::PosePriorErrorFunctionT< T > Class Template Reference
#include <pose_prior_error_function.h>
Public Member Functions
PosePriorErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, std::shared_ptr< const MppcaT< T > > pp)
PosePriorErrorFunctionT (const Character &character, std::shared_ptr< const MppcaT< T > > pp)
void setPosePrior (std::shared_ptr< const MppcaT< T > > pp)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final
double logProbability (const ModelParametersT< T > &params) const
double getJacobian (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
Eigen::VectorX< T > getMeanShape (const ModelParametersT< T > &params) const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Member Functions
void loadInternal ()
void getBestFitMode (const ModelParametersT< T > &params, size_t &bestIdx, Eigen::VectorX< T > &bestDiff, T &bestR, T &minDist) const
Protected Attributes
std::vector< size_t > ppMap_
std::vector< size_t > invMap_
std::shared_ptr< const MppcaT< T > > posePrior_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kPosePriorWeight = 1e-3
Detailed Description
template<typename T>
class momentum::PosePriorErrorFunctionT< T >
Definition at line 19 of file pose_prior_error_function.h.
Constructor & Destructor Documentation
PosePriorErrorFunctionT() [1/2]
template<typename T > momentum::PosePriorErrorFunctionT< T >::PosePriorErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, std::shared_ptr< const MppcaT< T > > pp)
Definition at line 17 of file pose_prior_error_function.cpp.
References momentum::PosePriorErrorFunctionT< T >::loadInternal(), and momentum::PosePriorErrorFunctionT< T >::posePrior_.
PosePriorErrorFunctionT() [2/2]
template<typename T > momentum::PosePriorErrorFunctionT< T >::PosePriorErrorFunctionT (const Character & character, std::shared_ptr< const MppcaT< T > > pp)
Definition at line 28 of file pose_prior_error_function.cpp.
Member Function Documentation
getBestFitMode()
template<typename T > void momentum::PosePriorErrorFunctionT< T >::getBestFitMode (const ModelParametersT< T > & params, size_t & bestIdx, Eigen::VectorX< T > & bestDiff, T & bestR, T & minDist) const protected
Definition at line 218 of file pose_prior_error_function.cpp.
References momentum::kInvalidIndex, and momentum::mapParameters().
Referenced by momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::d_gradient_d_input_dot().
getError()
template<typename T > double momentum::PosePriorErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 86 of file pose_prior_error_function.cpp.
getGradient()
template<typename T > double momentum::PosePriorErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 95 of file pose_prior_error_function.cpp.
References momentum::kInvalidIndex, and MT_PROFILE_FUNCTION.
getJacobian()
template<typename T > double momentum::PosePriorErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 147 of file pose_prior_error_function.cpp.
References momentum::kInvalidIndex, and MT_PROFILE_FUNCTION.
getJacobianSize()
template<typename T > size_t momentum::PosePriorErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 138 of file pose_prior_error_function.cpp.
getMeanShape()
template<typename T > Eigen::VectorX< T > momentum::PosePriorErrorFunctionT< T >::getMeanShape (const ModelParametersT< T > & params) const
Definition at line 204 of file pose_prior_error_function.cpp.
References momentum::kInvalidIndex.
loadInternal()
template<typename T > void momentum::PosePriorErrorFunctionT< T >::loadInternal () protected
Definition at line 41 of file pose_prior_error_function.cpp.
References momentum::kInvalidIndex.
Referenced by momentum::PosePriorErrorFunctionT< T >::PosePriorErrorFunctionT().
logProbability()
template<typename T > double momentum::PosePriorErrorFunctionT< T >::logProbability (const ModelParametersT< T > & params) const
Definition at line 68 of file pose_prior_error_function.cpp.
setPosePrior()
template<typename T > void momentum::PosePriorErrorFunctionT< T >::setPosePrior (std::shared_ptr< const MppcaT< T > > pp)
Definition at line 34 of file pose_prior_error_function.cpp.
Referenced by momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::setInputImp(), and momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::setPosePrior().
Member Data Documentation
invMap_
template<typename T > std::vector<size_t> momentum::PosePriorErrorFunctionT< T >::invMap_ protected
Definition at line 64 of file pose_prior_error_function.h.
kPosePriorWeight
template<typename T > constexpr T momentum::PosePriorErrorFunctionT< T >::kPosePriorWeight = 1e-3 static constexpr protected
Definition at line 73 of file pose_prior_error_function.h.
posePrior_
template<typename T > std::shared_ptr<const MppcaT<T> > momentum::PosePriorErrorFunctionT< T >::posePrior_ protected
Definition at line 70 of file pose_prior_error_function.h.
Referenced by momentum::PosePriorErrorFunctionT< T >::PosePriorErrorFunctionT().
ppMap_
template<typename T > std::vector<size_t> momentum::PosePriorErrorFunctionT< T >::ppMap_ protected
Definition at line 63 of file pose_prior_error_function.h.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/pose_prior_error_function.h
character_solver/pose_prior_error_function.cpp