Momentum: momentum::StateErrorFunctionT< T > Class Template Reference
momentum::StateErrorFunctionT< T > Class Template Reference
#include <state_error_function.h>
Public Member Functions
StateErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, RotationErrorType rotationErrorType=RotationErrorType::RotationMatrixDifference)
StateErrorFunctionT (const Character &character, RotationErrorType rotationErrorType=RotationErrorType::RotationMatrixDifference)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final
double getJacobian (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
void reset ()
void setTargetState (const SkeletonStateT< T > *target)
void setTargetState (const SkeletonStateT< T > &target)
void setTargetState (TransformListT< T > target)
void setTargetWeight (const Eigen::VectorX< T > &weights)
void setTargetWeights (const Eigen::VectorX< T > &posWeight, const Eigen::VectorX< T > &rotWeight)
void setPositionTargetWeights (const Eigen::VectorX< T > &posWeight)
Set the target position weights for each joint.
void setRotationTargetWeights (const Eigen::VectorX< T > &rotWeight)
Set the target rotation weights for each joint.
void setWeights (const float posWeight, const float rotationWeight)
const TransformListT< T > & getTargetState () const
const Eigen::VectorX< T > & getPositionWeights () const
const Eigen::VectorX< T > & getRotationWeights () const
const T & getPositionWeight () const
const T & getRotationWeight () const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Static Public Attributes
static constexpr T kPositionWeight = 1e-3f
static constexpr T kOrientationWeight = 1e+0f
Additional Inherited Members
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Detailed Description
template<typename T>
class momentum::StateErrorFunctionT< T >
Definition at line 35 of file state_error_function.h.
Constructor & Destructor Documentation
StateErrorFunctionT() [1/2]
template<typename T > momentum::StateErrorFunctionT< T >::StateErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, RotationErrorType rotationErrorType = RotationErrorType::RotationMatrixDifference)
Definition at line 126 of file state_error_function.cpp.
References momentum::SkeletonT< T >::joints, and momentum::SkeletonErrorFunctionT< T >::skeleton_.
StateErrorFunctionT() [2/2]
template<typename T > momentum::StateErrorFunctionT< T >::StateErrorFunctionT (const Character & character, RotationErrorType rotationErrorType = RotationErrorType::RotationMatrixDifference) explicit
Definition at line 138 of file state_error_function.cpp.
Member Function Documentation
getError()
template<typename T > double momentum::StateErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 199 of file state_error_function.cpp.
References momentum::kParametersPerJoint, momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), and momentum::RotationMatrixDifference.
getGradient()
template<typename T > double momentum::StateErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 265 of file state_error_function.cpp.
References momentum::gradient_jointParams_to_modelParams(), momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), momentum::quaternionLogMapDerivative(), and momentum::RotationMatrixDifference.
getJacobian()
template<typename T > double momentum::StateErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 407 of file state_error_function.cpp.
References momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), momentum::quaternionLogMapDerivative(), and momentum::RotationMatrixDifference.
getJacobianSize()
template<typename T > size_t momentum::StateErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 394 of file state_error_function.cpp.
References momentum::QuaternionLogMap.
getPositionWeight()
template<typename T > const T & momentum::StateErrorFunctionT< T >::getPositionWeight () const inline
Definition at line 96 of file state_error_function.h.
getPositionWeights()
template<typename T > const Eigen::VectorX< T > & momentum::StateErrorFunctionT< T >::getPositionWeights () const inline
Definition at line 90 of file state_error_function.h.
getRotationWeight()
template<typename T > const T & momentum::StateErrorFunctionT< T >::getRotationWeight () const inline
Definition at line 99 of file state_error_function.h.
getRotationWeights()
template<typename T > const Eigen::VectorX< T > & momentum::StateErrorFunctionT< T >::getRotationWeights () const inline
Definition at line 93 of file state_error_function.h.
getTargetState()
template<typename T > const TransformListT< T > & momentum::StateErrorFunctionT< T >::getTargetState () const inline
Definition at line 86 of file state_error_function.h.
reset()
template<typename T > void momentum::StateErrorFunctionT< T >::reset ()
Definition at line 144 of file state_error_function.cpp.
setPositionTargetWeights()
template<typename T > void momentum::StateErrorFunctionT< T >::setPositionTargetWeights (const Eigen::VectorX< T > & posWeight)
Set the target position weights for each joint.
Parameters
posWeight Per-joint position weights.
Definition at line 187 of file state_error_function.cpp.
References MT_CHECK.
setRotationTargetWeights()
template<typename T > void momentum::StateErrorFunctionT< T >::setRotationTargetWeights (const Eigen::VectorX< T > & rotWeight)
Set the target rotation weights for each joint.
Parameters
rotWeight Per-joint rotation weights.
Definition at line 193 of file state_error_function.cpp.
References MT_CHECK.
setTargetState() [1/3]
template<typename T > void momentum::StateErrorFunctionT< T >::setTargetState (const SkeletonStateT< T > & target)
Definition at line 156 of file state_error_function.cpp.
References momentum::SkeletonStateT< T >::jointState, MT_CHECK, and momentum::SkeletonStateT< T >::toTransforms().
setTargetState() [2/3]
template<typename T > void momentum::StateErrorFunctionT< T >::setTargetState (const SkeletonStateT< T > * target)
Definition at line 150 of file state_error_function.cpp.
References MT_CHECK.
setTargetState() [3/3]
template<typename T > void momentum::StateErrorFunctionT< T >::setTargetState (TransformListT< T > target)
Definition at line 162 of file state_error_function.cpp.
References MT_CHECK.
setTargetWeight()
template<typename T > void momentum::StateErrorFunctionT< T >::setTargetWeight (const Eigen::VectorX< T > & weights)
Definition at line 168 of file state_error_function.cpp.
References MT_CHECK.
setTargetWeights()
template<typename T > void momentum::StateErrorFunctionT< T >::setTargetWeights (const Eigen::VectorX< T > & posWeight, const Eigen::VectorX< T > & rotWeight)
Definition at line 176 of file state_error_function.cpp.
References MT_CHECK.
setWeights()
template<typename T > void momentum::StateErrorFunctionT< T >::setWeights (const float posWeight, const float rotationWeight) inline
Definition at line 81 of file state_error_function.h.
Member Data Documentation
kOrientationWeight
template<typename T > constexpr T momentum::StateErrorFunctionT< T >::kOrientationWeight = 1e+0f static constexpr
Definition at line 116 of file state_error_function.h.
kPositionWeight
template<typename T > constexpr T momentum::StateErrorFunctionT< T >::kPositionWeight = 1e-3f static constexpr
Definition at line 115 of file state_error_function.h.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/state_error_function.h
character_solver/state_error_function.cpp