Momentum: momentum::SolverT< T > Class Template Reference
momentum::SolverT< T > Class Template Reference abstract
Base class for numerical optimization solvers.
#include <solver.h>
Public Member Functions
SolverT (const SolverOptions &options, SolverFunctionT< T > *solver)
Constructor with solver options and function to optimize.
virtual ~SolverT ()=default
virtual std::string_view getName () const =0
Returns the name of the solver implementation.
virtual void setOptions (const SolverOptions &options)
Updates solver configuration with new options.
double solve (Eigen::VectorX< T > &params)
Solves the optimization problem.
virtual void setEnabledParameters (const ParameterSet &parameters)
Specifies which parameters should be optimized.
const ParameterSet & getActiveParameters () const
Returns the current set of enabled parameters.
void setParameters (const Eigen::VectorX< T > &params)
Sets the current parameter values without solving.
void setStoreHistory (bool b)
Controls whether to store iteration history for debugging and analysis.
const std::unordered_map< std::string, Eigen::MatrixX< T > > & getHistory () const
Returns the history of the solver's iterations.
size_t getMinIterations () const
Returns the minimum number of iterations before checking convergence.
size_t getMaxIterations () const
Returns the maximum number of iterations before terminating.
size_t getNumParameters () const
const std::vector< double > & getErrorHistory () const
Returns the history of objective function values over the iterations of the solve.
Protected Member Functions
virtual void initializeSolver ()=0
Initializes solver state before optimization begins.
virtual void doIteration ()=0
Performs a single iteration of the optimization algorithm.
Protected Attributes
size_t numParameters_
Total number of parameters in the optimization problem.
SolverFunctionT< T > * solverFunction_
Function to be optimized.
Eigen::VectorX< T > parameters_
Current parameter values.
ParameterSet activeParameters_
Bitset indicating which parameters are enabled for optimization.
int actualParameters_
Number of parameters currently enabled for optimization.
bool newParameterPattern_
Flag indicating parameter structure has changed.
size_t iteration_ {}
Current iteration count.
double error_ {}
Current objective function value.
double lastError_ {}
Previous iteration's objective function value.
bool storeHistory = false
Whether to record optimization progress for analysis.
std::unordered_map< std::string, Eigen::MatrixX< T > > iterationHistory_
Recorded data from optimization process.
std::vector< double > errorHistory_
History of objective function values over the iterations.
bool verbose_ = false
Whether to output detailed progress information.
Detailed Description
template<typename T>
class momentum::SolverT< T >
Base class for numerical optimization solvers.
Provides common functionality for iterative optimization algorithms including parameter management, convergence checking, and history tracking.
Definition at line 41 of file solver.h.
Constructor & Destructor Documentation
SolverT()
template<typename T > momentum::SolverT< T >::SolverT (const SolverOptions & options, SolverFunctionT< T > * solver)
Constructor with solver options and function to optimize.
Definition at line 20 of file solver.cpp.
References momentum::SolverT< T >::activeParameters_, momentum::SolverT< T >::actualParameters_, momentum::SolverT< T >::newParameterPattern_, momentum::SolverT< T >::numParameters_, momentum::SolverT< T >::parameters_, momentum::SolverT< T >::setOptions(), and momentum::SolverT< T >::solverFunction_.
~SolverT()
template<typename T > virtual momentum::SolverT< T >::~SolverT () virtual default
Member Function Documentation
doIteration()
template<typename T > virtual void momentum::SolverT< T >::doIteration () protected pure virtual
Performs a single iteration of the optimization algorithm.
Implemented in momentum::MultiposeSolverT< T >, momentum::SequenceSolverT< T >, momentum::GaussNewtonSolverQRT< T >, momentum::TrustRegionQRT< T >, momentum::GaussNewtonSolverT< T >, momentum::GradientDescentSolverT< T >, and momentum::SubsetGaussNewtonSolverT< T >.
getActiveParameters()
template<typename T > const ParameterSet & momentum::SolverT< T >::getActiveParameters () const
Returns the current set of enabled parameters.
Definition at line 131 of file solver.cpp.
getErrorHistory()
template<typename T > const std::vector< double > & momentum::SolverT< T >::getErrorHistory () const inline
Returns the history of objective function values over the iterations of the solve.
Definition at line 90 of file solver.h.
References momentum::SolverT< T >::errorHistory_.
getHistory()
template<typename T > const std::unordered_map< std::string, Eigen::MatrixX< T > > & momentum::SolverT< T >::getHistory () const
Returns the history of the solver's iterations.
The history contains matrices for parameters, errors, and other solver-specific data
Definition at line 146 of file solver.cpp.
getMaxIterations()
template<typename T > size_t momentum::SolverT< T >::getMaxIterations () const
Returns the maximum number of iterations before terminating.
Definition at line 156 of file solver.cpp.
getMinIterations()
template<typename T > size_t momentum::SolverT< T >::getMinIterations () const
Returns the minimum number of iterations before checking convergence.
Definition at line 151 of file solver.cpp.
getName()
template<typename T > virtual std::string_view momentum::SolverT< T >::getName () const pure virtual
Returns the name of the solver implementation.
Implemented in momentum::MultiposeSolverT< T >, momentum::SequenceSolverT< T >, momentum::GaussNewtonSolverQRT< T >, momentum::TrustRegionQRT< T >, momentum::GaussNewtonSolverT< T >, momentum::GradientDescentSolverT< T >, and momentum::SubsetGaussNewtonSolverT< T >.
getNumParameters()
template<typename T > size_t momentum::SolverT< T >::getNumParameters () const inline
Definition at line 85 of file solver.h.
References momentum::SolverT< T >::numParameters_.
initializeSolver()
template<typename T > virtual void momentum::SolverT< T >::initializeSolver () protected pure virtual
Initializes solver state before optimization begins.
Implemented in momentum::MultiposeSolverT< T >, momentum::SequenceSolverT< T >, momentum::GaussNewtonSolverQRT< T >, momentum::TrustRegionQRT< T >, momentum::GaussNewtonSolverT< T >, momentum::GradientDescentSolverT< T >, and momentum::SubsetGaussNewtonSolverT< T >.
setEnabledParameters()
template<typename T > void momentum::SolverT< T >::setEnabledParameters (const ParameterSet & parameters) virtual
Specifies which parameters should be optimized.
Parameters
parameters Bitset where each bit indicates if the corresponding parameter is enabled
Reimplemented in momentum::SequenceSolverT< T >, and momentum::SubsetGaussNewtonSolverT< T >.
Definition at line 40 of file solver.cpp.
Referenced by momentum::SequenceSolverT< T >::setEnabledParameters(), and momentum::SubsetGaussNewtonSolverT< T >::setEnabledParameters().
setOptions()
template<typename T > void momentum::SolverT< T >::setOptions (const SolverOptions & options) virtual
Updates solver configuration with new options.
Reimplemented in momentum::MultiposeSolverT< T >, momentum::SequenceSolverT< T >, momentum::GaussNewtonSolverQRT< T >, momentum::TrustRegionQRT< T >, momentum::GaussNewtonSolverT< T >, momentum::GradientDescentSolverT< T >, and momentum::SubsetGaussNewtonSolverT< T >.
Definition at line 32 of file solver.cpp.
Referenced by momentum::MultiposeSolverT< T >::setOptions(), momentum::SequenceSolverT< T >::setOptions(), momentum::GaussNewtonSolverQRT< T >::setOptions(), momentum::TrustRegionQRT< T >::setOptions(), momentum::GaussNewtonSolverT< T >::setOptions(), momentum::GradientDescentSolverT< T >::setOptions(), momentum::SubsetGaussNewtonSolverT< T >::setOptions(), and momentum::SolverT< T >::SolverT().
setParameters()
template<typename T > void momentum::SolverT< T >::setParameters (const Eigen::VectorX< T > & params)
Sets the current parameter values without solving.
Definition at line 136 of file solver.cpp.
setStoreHistory()
template<typename T > void momentum::SolverT< T >::setStoreHistory (bool b)
Controls whether to store iteration history for debugging and analysis.
Definition at line 141 of file solver.cpp.
solve()
template<typename T > double momentum::SolverT< T >::solve (Eigen::VectorX< T > & params)
Solves the optimization problem.
Parameters
[in,out] params Vector of initial guess, updated with the optimized solution
Returns
Final objective function value after optimization
Definition at line 50 of file solver.cpp.
References MT_CHECK, MT_LOGI_IF, and MT_PROFILE_FUNCTION.
Member Data Documentation
activeParameters_
template<typename T > ParameterSet momentum::SolverT< T >::activeParameters_ protected
Bitset indicating which parameters are enabled for optimization.
Definition at line 112 of file solver.h.
Referenced by momentum::SolverT< T >::SolverT().
actualParameters_
template<typename T > int momentum::SolverT< T >::actualParameters_ protected
Number of parameters currently enabled for optimization.
Definition at line 115 of file solver.h.
Referenced by momentum::SolverT< T >::SolverT().
error_
template<typename T > double momentum::SolverT< T >::error_ {} protected
Current objective function value.
Definition at line 126 of file solver.h.
errorHistory_
template<typename T > std::vector<double> momentum::SolverT< T >::errorHistory_ protected
History of objective function values over the iterations.
Definition at line 139 of file solver.h.
Referenced by momentum::SolverT< T >::getErrorHistory().
iteration_
template<typename T > size_t momentum::SolverT< T >::iteration_ {} protected
Current iteration count.
Definition at line 123 of file solver.h.
Referenced by momentum::MultiposeSolverT< T >::init(), momentum::SequenceSolverT< T >::init(), momentum::TrustRegionQRT< T >::init(), momentum::MultiposeSolverT< T >::iter(), momentum::SequenceSolverT< T >::iter(), and momentum::TrustRegionQRT< T >::iter().
iterationHistory_
template<typename T > std::unordered_map<std::string, Eigen::MatrixX<T> > momentum::SolverT< T >::iterationHistory_ protected
Recorded data from optimization process.
Contains matrices for parameters, errors, and other solver-specific data
Definition at line 137 of file solver.h.
lastError_
template<typename T > double momentum::SolverT< T >::lastError_ {} protected
Previous iteration's objective function value.
Definition at line 129 of file solver.h.
newParameterPattern_
template<typename T > bool momentum::SolverT< T >::newParameterPattern_ protected
Flag indicating parameter structure has changed.
Used to trigger reinitialization of solver data structures
Definition at line 120 of file solver.h.
Referenced by momentum::SolverT< T >::SolverT().
numParameters_
template<typename T > size_t momentum::SolverT< T >::numParameters_ protected
Total number of parameters in the optimization problem.
Definition at line 103 of file solver.h.
Referenced by momentum::SolverT< T >::getNumParameters(), momentum::SequenceSolverT< T >::setEnabledParameters(), and momentum::SolverT< T >::SolverT().
parameters_
template<typename T > Eigen::VectorX<T> momentum::SolverT< T >::parameters_ protected
Current parameter values.
Definition at line 109 of file solver.h.
Referenced by momentum::MultiposeSolverT< T >::getP(), momentum::SequenceSolverT< T >::getP(), momentum::TrustRegionQRT< T >::getP(), and momentum::SolverT< T >::SolverT().
solverFunction_
template<typename T > SolverFunctionT<T>* momentum::SolverT< T >::solverFunction_ protected
Function to be optimized.
Definition at line 106 of file solver.h.
Referenced by momentum::SequenceSolverT< T >::setEnabledParameters(), and momentum::SolverT< T >::SolverT().
storeHistory
template<typename T > bool momentum::SolverT< T >::storeHistory = false protected
Whether to record optimization progress for analysis.
Definition at line 132 of file solver.h.
verbose_
template<typename T > bool momentum::SolverT< T >::verbose_ = false protected
Whether to output detailed progress information.
Definition at line 142 of file solver.h.
The documentation for this class was generated from the following files:
solver/fwd.h
solver/solver.h
solver/solver.cpp