Momentum: momentum::CollisionErrorFunctionStatelessT< T > Class Template Reference
momentum::CollisionErrorFunctionStatelessT< T > Class Template Reference
NOTE: This is a resurrected version of the CollisionErrorFunction (previously updated by D50818775).
#include <collision_error_function_stateless.h>
Public Member Functions
CollisionErrorFunctionStatelessT (const Skeleton &skel, const ParameterTransform &pt, const CollisionGeometry &cg)
CollisionErrorFunctionStatelessT (const Character &character)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< VectorX< T > > gradient) override
double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int &usedRows) override
size_t getJacobianSize () const final
std::vector< Vector2i > getCollisionPairs () const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Member Functions
void updateCollisionPairs ()
Protected Attributes
const CollisionGeometry collisionGeometry
std::vector< Vector3i > collisionPairs
VectorX< bool > collisionActive
CollisionGeometryStateT< T > collisionState
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kCollisionWeight = 5e-3f
Detailed Description
template<typename T>
class momentum::CollisionErrorFunctionStatelessT< T >
NOTE: This is a resurrected version of the CollisionErrorFunction (previously updated by D50818775).
Its stateless nature makes it ideal for testing in multi-threaded settings.
Represents an error function that penalizes self-intersections between collision geometries of the character.
The function pre-filters collision geometries to ignore those attached to the same joint, those intersecting in the rest pose, or those very close in the rest pose.
Definition at line 26 of file collision_error_function_stateless.h.
Constructor & Destructor Documentation
CollisionErrorFunctionStatelessT() [1/2]
template<typename T > momentum::CollisionErrorFunctionStatelessT< T >::CollisionErrorFunctionStatelessT (const Skeleton & skel, const ParameterTransform & pt, const CollisionGeometry & cg) explicit
Definition at line 20 of file collision_error_function_stateless.cpp.
References momentum::CollisionErrorFunctionStatelessT< T >::updateCollisionPairs().
CollisionErrorFunctionStatelessT() [2/2]
template<typename T > momentum::CollisionErrorFunctionStatelessT< T >::CollisionErrorFunctionStatelessT (const Character & character) explicit
Definition at line 29 of file collision_error_function_stateless.cpp.
Member Function Documentation
getCollisionPairs()
template<typename T > std::vector< Vector2i > momentum::CollisionErrorFunctionStatelessT< T >::getCollisionPairs () const
Definition at line 105 of file collision_error_function_stateless.cpp.
getError()
template<typename T > double momentum::CollisionErrorFunctionStatelessT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 118 of file collision_error_function_stateless.cpp.
References distance, momentum::kParametersPerJoint, MT_CHECK, momentum::overlaps(), and momentum::sqr().
getGradient()
template<typename T > double momentum::CollisionErrorFunctionStatelessT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< VectorX< T > > gradient) override
Definition at line 167 of file collision_error_function_stateless.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, momentum::overlaps(), and momentum::sqr().
getJacobian()
template<typename T > double momentum::CollisionErrorFunctionStatelessT< T >::getJacobian (const ModelParametersT< T > & , const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int & usedRows) override
Definition at line 337 of file collision_error_function_stateless.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_EVENT, MT_PROFILE_FUNCTION, momentum::overlaps(), and momentum::sqr().
getJacobianSize()
template<typename T > size_t momentum::CollisionErrorFunctionStatelessT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 534 of file collision_error_function_stateless.cpp.
updateCollisionPairs()
template<typename T > void momentum::CollisionErrorFunctionStatelessT< T >::updateCollisionPairs () protected
Definition at line 41 of file collision_error_function_stateless.cpp.
References distance, and momentum::overlaps().
Referenced by momentum::CollisionErrorFunctionStatelessT< T >::CollisionErrorFunctionStatelessT().
Member Data Documentation
collisionActive
template<typename T > VectorX<bool> momentum::CollisionErrorFunctionStatelessT< T >::collisionActive protected
Definition at line 67 of file collision_error_function_stateless.h.
collisionGeometry
template<typename T > const CollisionGeometry momentum::CollisionErrorFunctionStatelessT< T >::collisionGeometry protected
Definition at line 61 of file collision_error_function_stateless.h.
collisionPairs
template<typename T > std::vector<Vector3i> momentum::CollisionErrorFunctionStatelessT< T >::collisionPairs protected
Definition at line 65 of file collision_error_function_stateless.h.
collisionState
template<typename T > CollisionGeometryStateT<T> momentum::CollisionErrorFunctionStatelessT< T >::collisionState protected
Definition at line 69 of file collision_error_function_stateless.h.
kCollisionWeight
template<typename T > constexpr T momentum::CollisionErrorFunctionStatelessT< T >::kCollisionWeight = 5e-3f static constexpr protected
Definition at line 72 of file collision_error_function_stateless.h.
The documentation for this class was generated from the following files:
character_solver/collision_error_function_stateless.h
character_solver/collision_error_function_stateless.cpp