Momentum: momentum::ResizeableMatrix< T > Class Template Reference
momentum::ResizeableMatrix< T > Class Template Reference
#include <online_householder_qr.h>
Public Types
using MatrixType = Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic >
Public Member Functions
ResizeableMatrix ()=default
ResizeableMatrix (Eigen::Index rows, Eigen::Index cols=1)
void resizeAndSetZero (Eigen::Index rows, Eigen::Index cols=1)
Eigen::Index rows () const
Eigen::Index cols () const
Eigen::Map< MatrixType, Eigen::Aligned16 > mat ()
Eigen::Map< const MatrixType, Eigen::Aligned16 > mat () const
Detailed Description
template<typename T>
class momentum::ResizeableMatrix< T >
Definition at line 85 of file online_householder_qr.h.
Member Typedef Documentation
MatrixType
template<typename T > using momentum::ResizeableMatrix< T >::MatrixType = Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>
Definition at line 87 of file online_householder_qr.h.
Constructor & Destructor Documentation
ResizeableMatrix() [1/2]
template<typename T > momentum::ResizeableMatrix< T >::ResizeableMatrix () default
ResizeableMatrix() [2/2]
template<typename T > momentum::ResizeableMatrix< T >::ResizeableMatrix (Eigen::Index rows, Eigen::Index cols = 1) inline explicit
Definition at line 90 of file online_householder_qr.h.
References momentum::ResizeableMatrix< T >::cols(), momentum::ResizeableMatrix< T >::resizeAndSetZero(), and momentum::ResizeableMatrix< T >::rows().
Member Function Documentation
cols()
template<typename T > Eigen::Index momentum::ResizeableMatrix< T >::cols () const inline
Definition at line 106 of file online_householder_qr.h.
Referenced by momentum::ResizeableMatrix< T >::ResizeableMatrix(), and momentum::ResizeableMatrix< T >::resizeAndSetZero().
mat() [1/2]
template<typename T > Eigen::Map< MatrixType, Eigen::Aligned16 > momentum::ResizeableMatrix< T >::mat () inline
Definition at line 110 of file online_householder_qr.h.
mat() [2/2]
template<typename T > Eigen::Map< const MatrixType, Eigen::Aligned16 > momentum::ResizeableMatrix< T >::mat () const inline
Definition at line 113 of file online_householder_qr.h.
resizeAndSetZero()
template<typename T > void momentum::ResizeableMatrix< T >::resizeAndSetZero (Eigen::Index rows, Eigen::Index cols = 1) inline
Definition at line 94 of file online_householder_qr.h.
References momentum::ResizeableMatrix< T >::cols(), and momentum::ResizeableMatrix< T >::rows().
Referenced by momentum::ResizeableMatrix< T >::ResizeableMatrix().
rows()
template<typename T > Eigen::Index momentum::ResizeableMatrix< T >::rows () const inline
Definition at line 103 of file online_householder_qr.h.
Referenced by momentum::ResizeableMatrix< T >::ResizeableMatrix(), and momentum::ResizeableMatrix< T >::resizeAndSetZero().
The documentation for this class was generated from the following file:
math/online_householder_qr.h