Momentum: momentum::FullyDifferentiablePosePriorErrorFunctionT< T > Class Template Reference
momentum::FullyDifferentiablePosePriorErrorFunctionT< T > Class Template Reference
#include <fully_differentiable_pose_prior_error_function.h>
Public Member Functions
FullyDifferentiablePosePriorErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, std::vector< std::string > names)
~FullyDifferentiablePosePriorErrorFunctionT () override
void setPosePrior (const VectorX< T > &pi, const MatrixX< T > &mmu, const std::vector< MatrixX< T > > &W, const VectorX< T > &sigma)
std::vector< std::string > inputs () const final
Eigen::Index getInputSize (const std::string &name) const final
const char * name () const final
Eigen::VectorX< T > d_gradient_d_input_dot (const std::string &inputName, const ModelParametersT< T > &params, const SkeletonStateT< T > &state, Eigen::Ref< const Eigen::VectorX< T > > inputVec) final
Public Member Functions inherited from momentum::FullyDifferentiableSkeletonErrorFunctionT< T >
virtual ~FullyDifferentiableSkeletonErrorFunctionT ()=default
Eigen::VectorX< T > getInput (const std::string &name) const
void getInput (const std::string &name, Eigen::Ref< Eigen::VectorX< T > > value) const
void setInput (const std::string &name, Eigen::Ref< const Eigen::VectorX< T > > value)
Public Member Functions inherited from momentum::PosePriorErrorFunctionT< T >
PosePriorErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, std::shared_ptr< const MppcaT< T > > pp)
PosePriorErrorFunctionT (const Character &character, std::shared_ptr< const MppcaT< T > > pp)
void setPosePrior (std::shared_ptr< const MppcaT< T > > pp)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final
double logProbability (const ModelParametersT< T > &params) const
double getJacobian (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
Eigen::VectorX< T > getMeanShape (const ModelParametersT< T > &params) const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Static Public Attributes
static constexpr const char * kPi = "pi"
static constexpr const char * kMu = "mu"
static constexpr const char * kW = "W"
static constexpr const char * kSigma = "sigma"
static constexpr const char * kParameterIndices = "parameter_indices"
Protected Member Functions
void getInputImp (const std::string &name, Eigen::Ref< Eigen::VectorX< T > > value) const final
void setInputImp (const std::string &name, Eigen::Ref< const Eigen::VectorX< T > > value) final
Protected Member Functions inherited from momentum::PosePriorErrorFunctionT< T >
void loadInternal ()
void getBestFitMode (const ModelParametersT< T > &params, size_t &bestIdx, Eigen::VectorX< T > &bestDiff, T &bestR, T &minDist) const
Protected Attributes
Eigen::VectorX< T > pi_
Eigen::MatrixX< T > mmu_
std::vector< Eigen::MatrixX< T > > W_
Eigen::VectorX< T > sigma_
const std::vector< std::string > names_
Protected Attributes inherited from momentum::PosePriorErrorFunctionT< T >
std::vector< size_t > ppMap_
std::vector< size_t > invMap_
std::shared_ptr< const MppcaT< T > > posePrior_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Additional Inherited Members
Static Protected Attributes inherited from momentum::PosePriorErrorFunctionT< T >
static constexpr T kPosePriorWeight = 1e-3
Detailed Description
template<typename T>
class momentum::FullyDifferentiablePosePriorErrorFunctionT< T >
Definition at line 20 of file fully_differentiable_pose_prior_error_function.h.
Constructor & Destructor Documentation
FullyDifferentiablePosePriorErrorFunctionT()
template<typename T > momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::FullyDifferentiablePosePriorErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, std::vector< std::string > names)
Definition at line 34 of file fully_differentiable_pose_prior_error_function.cpp.
~FullyDifferentiablePosePriorErrorFunctionT()
template<typename T > momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::~FullyDifferentiablePosePriorErrorFunctionT () override default
Member Function Documentation
d_gradient_d_input_dot()
template<typename T > Eigen::VectorX< T > momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::d_gradient_d_input_dot (const std::string & inputName, const ModelParametersT< T > & params, const SkeletonStateT< T > & state, Eigen::Ref< const Eigen::VectorX< T > > inputVec) final virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 190 of file fully_differentiable_pose_prior_error_function.cpp.
References momentum::PosePriorErrorFunctionT< T >::getBestFitMode(), momentum::kInvalidIndex, MT_CHECK, and MT_THROW_IF.
getInputImp()
template<typename T > void momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::getInputImp (const std::string & name, Eigen::Ref< Eigen::VectorX< T > > value) const final protected virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 100 of file fully_differentiable_pose_prior_error_function.cpp.
References MT_CHECK, MT_THROW, and MT_THROW_IF.
getInputSize()
template<typename T > Eigen::Index momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::getInputSize (const std::string & name) const final virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 79 of file fully_differentiable_pose_prior_error_function.cpp.
References MT_THROW.
inputs()
template<typename T > std::vector< std::string > momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::inputs () const final virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 74 of file fully_differentiable_pose_prior_error_function.cpp.
name()
template<typename T > const char * momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::name () const inline final virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 44 of file fully_differentiable_pose_prior_error_function.h.
setInputImp()
template<typename T > void momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::setInputImp (const std::string & name, Eigen::Ref< const Eigen::VectorX< T > > value) final protected virtual
Implements momentum::FullyDifferentiableSkeletonErrorFunctionT< T >.
Definition at line 142 of file fully_differentiable_pose_prior_error_function.cpp.
References MT_CHECK, MT_THROW, MT_THROW_IF, and momentum::PosePriorErrorFunctionT< T >::setPosePrior().
setPosePrior()
template<typename T > void momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::setPosePrior (const VectorX< T > & pi, const MatrixX< T > & mmu, const std::vector< MatrixX< T > > & W, const VectorX< T > & sigma)
Definition at line 46 of file fully_differentiable_pose_prior_error_function.cpp.
References MT_THROW_IF, momentum::pi(), and momentum::PosePriorErrorFunctionT< T >::setPosePrior().
Member Data Documentation
kMu
template<typename T > constexpr const char* momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::kMu = "mu" static constexpr
Definition at line 37 of file fully_differentiable_pose_prior_error_function.h.
kParameterIndices
template<typename T > constexpr const char* momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::kParameterIndices = "parameter_indices" static constexpr
Definition at line 40 of file fully_differentiable_pose_prior_error_function.h.
kPi
template<typename T > constexpr const char* momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::kPi = "pi" static constexpr
Definition at line 36 of file fully_differentiable_pose_prior_error_function.h.
kSigma
template<typename T > constexpr const char* momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::kSigma = "sigma" static constexpr
Definition at line 39 of file fully_differentiable_pose_prior_error_function.h.
kW
template<typename T > constexpr const char* momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::kW = "W" static constexpr
Definition at line 38 of file fully_differentiable_pose_prior_error_function.h.
mmu_
template<typename T > Eigen::MatrixX<T> momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::mmu_ protected
Definition at line 62 of file fully_differentiable_pose_prior_error_function.h.
names_
template<typename T > const std::vector<std::string> momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::names_ protected
Definition at line 73 of file fully_differentiable_pose_prior_error_function.h.
pi_
template<typename T > Eigen::VectorX<T> momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::pi_ protected
Definition at line 59 of file fully_differentiable_pose_prior_error_function.h.
sigma_
template<typename T > Eigen::VectorX<T> momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::sigma_ protected
Definition at line 71 of file fully_differentiable_pose_prior_error_function.h.
W_
template<typename T > std::vector<Eigen::MatrixX<T> > momentum::FullyDifferentiablePosePriorErrorFunctionT< T >::W_ protected
Definition at line 65 of file fully_differentiable_pose_prior_error_function.h.
The documentation for this class was generated from the following files:
diff_ik/fully_differentiable_pose_prior_error_function.h
diff_ik/fully_differentiable_pose_prior_error_function.cpp