Momentum: momentum::Random< Generator_ > Class Template Reference
momentum::Random< Generator_ > Class Template Reference final
A consolidated random number generator to provide convenient APIs wrapping around the random library of C++ standard library <random>.
#include <random.h>
Public Types
using Generator = Generator_
Public Member Functions
Random (uint32_t seed=std::random_device{}())
Constructor.
template<typename T >
T uniform (const T &min, const T &max)
Generates a random scalar/vector/matrix from the uniform distribution.
template<typename FixedSizeT >
FixedSizeT uniform (typename FixedSizeT::Scalar min, typename FixedSizeT::Scalar max)
Generates a random vector/matrix from the uniform distribution, where the size is fixed.
template<typename DynamicVector >
DynamicVector uniform (Eigen::Index size, typename DynamicVector::Scalar min, typename DynamicVector::Scalar max)
Generates a random vector from the uniform distribution, where the size is dynamic.
template<typename DynamicMatrix >
DynamicMatrix uniform (Eigen::Index rows, Eigen::Index cols, typename DynamicMatrix::Scalar min, typename DynamicMatrix::Scalar max)
Generates a random matrix from the uniform distribution, where the size is dynamic.
template<typename T >
Quaternion< T > uniformQuaternion ()
Generates a random quaternion from a uniform distribution on SO(3)
template<typename T >
Matrix3< T > uniformRotationMatrix ()
Generates a random rotation matrix from a uniform distribution on SO(3)
template<typename T >
Isometry3< T > uniformIsometry3 (const Vector3< T > &min=Vector3< T >::Zero(), const Vector3< T > &max=Vector3< T >::Ones())
Generates a random isometry (rigid transformation) from a uniform distribution on SE(3) based on input minimum and maximum 3D vectors for the translation part.
template<typename T >
Affine3< T > uniformAffine3 (T scaleMin=0.1, T scaleMax=10.0, const Vector3< T > &min=Vector3< T >::Zero(), const Vector3< T > &max=Vector3< T >::Ones())
Generates a random affine transformation from a uniform distribution on the space of all affine transformations.
template<typename T >
T normal (const T &mean, const T &sigma)
Generates a random value from the Gaussian distribution.
template<typename FixedSizeT >
FixedSizeT normal (typename FixedSizeT::Scalar mean, typename FixedSizeT::Scalar sigma)
Generates a random value from the Gaussian distribution.
template<typename DynamicVector >
DynamicVector normal (Eigen::Index size, typename DynamicVector::Scalar mean, typename DynamicVector::Scalar sigma)
Generates a random value from the Gaussian distribution.
template<typename DynamicMatrix >
DynamicMatrix normal (Eigen::Index rows, Eigen::Index cols, typename DynamicMatrix::Scalar mean, typename DynamicMatrix::Scalar sigma)
Generates a random value from the Gaussian distribution.
uint32_t getSeed () const
Returns the seed.
void setSeed (uint32_t seed)
Sets a new seed for the internal random number engine.
Static Public Member Functions
static Random & GetSingleton ()
Returns the singleton instance.
Detailed Description
template<typename Generator_ = std::mt19937>
class momentum::Random< Generator_ >
A consolidated random number generator to provide convenient APIs wrapping around the random library of C++ standard library <random>.
The default engine used in this class is std::mt19937, but it can be replaced, by specifying the template argument, with any preferable engines (see: https://en.cppreference.com/w/cpp/numeric/random).
Definition at line 23 of file random.h.
Member Typedef Documentation
Generator
template<typename Generator_ = std::mt19937> using momentum::Random< Generator_ >::Generator = Generator_
Definition at line 25 of file random.h.
Constructor & Destructor Documentation
Random()
template<typename Generator > momentum::Random< Generator >::Random (uint32_t seed = std::random_device{}()) explicit
Constructor.
Definition at line 193 of file random-inl.h.
Member Function Documentation
getSeed()
template<typename Generator > uint32_t momentum::Random< Generator >::getSeed () const
Returns the seed.
Definition at line 308 of file random-inl.h.
GetSingleton()
template<typename Generator > Random< Generator > & momentum::Random< Generator >::GetSingleton () static
Returns the singleton instance.
Definition at line 187 of file random-inl.h.
Referenced by momentum::normal(), momentum::normal(), momentum::normal(), momentum::normal(), momentum::uniform(), momentum::uniform(), momentum::uniform(), momentum::uniform(), momentum::uniformAffine3(), momentum::uniformIsometry3(), and momentum::uniformQuaternion().
normal() [1/4]
template<typename Generator > template<typename T > T momentum::Random< Generator >::normal (const T & mean, const T & sigma)
Generates a random value from the Gaussian distribution.
Template Parameters
T The random number type to be generated
Parameters
[in] mean The mean of the Gaussian distribution
[in] sigma The standard deviation of the Gaussian distribution
Definition at line 271 of file random-inl.h.
References momentum::detail::generateNormal().
normal() [2/4]
template<typename Generator > template<typename DynamicMatrix > DynamicMatrix momentum::Random< Generator >::normal (Eigen::Index rows, Eigen::Index cols, typename DynamicMatrix::Scalar mean, typename DynamicMatrix::Scalar sigma)
Generates a random value from the Gaussian distribution.
Template Parameters
DynamicMatrix The random matrix type to be generated
Parameters
[in] rows The row size of the matrix.
[in] cols The column size of the matrix.
[in] mean The mean of the Gaussian distribution
[in] sigma The standard deviation of the Gaussian distribution
Definition at line 296 of file random-inl.h.
References momentum::detail::generateMatrixNormal().
normal() [3/4]
template<typename Generator > template<typename DynamicVector > DynamicVector momentum::Random< Generator >::normal (Eigen::Index size, typename DynamicVector::Scalar mean, typename DynamicVector::Scalar sigma)
Generates a random value from the Gaussian distribution.
Template Parameters
DynamicVector The random vector type to be generated
Parameters
[in] size The size of the vector.
[in] mean The mean of the Gaussian distribution
[in] sigma The standard deviation of the Gaussian distribution
Definition at line 286 of file random-inl.h.
References momentum::detail::generateMatrixNormal().
normal() [4/4]
template<typename Generator > template<typename FixedSizeT > FixedSizeT momentum::Random< Generator >::normal (typename FixedSizeT::Scalar mean, typename FixedSizeT::Scalar sigma)
Generates a random value from the Gaussian distribution.
Template Parameters
FixedSizeT The random vector/matrix type to be generated
Parameters
[in] mean The mean of the Gaussian distribution
[in] sigma The standard deviation of the Gaussian distribution
Definition at line 277 of file random-inl.h.
References momentum::detail::generateMatrixNormal().
setSeed()
template<typename Generator > void momentum::Random< Generator >::setSeed (uint32_t seed)
Sets a new seed for the internal random number engine.
Definition at line 313 of file random-inl.h.
uniform() [1/4]
template<typename Generator > template<typename T > T momentum::Random< Generator >::uniform (const T & min, const T & max)
Generates a random scalar/vector/matrix from the uniform distribution.
The supported types are scalar, vector, or matrix where the elements can be either integer or real. The supported integer types are whichever supported by std::uniform_int_distribution<T> (see: https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution), and the supported real types are whichever std::is_floating_point<T>::value is true (see: https://en.cppreference.com/w/cpp/types/is_floating_point).
The generated random number is in the range of [min, max] for integer types or [min, max) for real types. However, when built with the -ffast-math flag, the range for real types could be [min, max] instead.
Warning
While the upper bound is typically exclusive for real types according to std::uniform_real_distribution, there may be instances where the sampled value equals the upper bound, depending on the platform and compiler specifics.
For vector/matrix types, the bounds can be specified in either scalar or (the same dimension of) vector/matrix. Use this function to specify the bounds in vector/matrix to apply different bounds for each element in the generated vector/matrix. Use other versions of uniform() that specify the bounds in scalar to apply the same bounds to all the elements of the generated vector/matrix.
Random rand;
auto r0 = rand.uniform(0.0, 1.0); // random double in [0, 1)
auto r1 = rand.uniform(0.f, 1.f); // random float in [0, 1)
auto r3 = rand.uniform(0, 10);    // random int in [0, 10]
auto r4 = rand.uniform(Vector2f(0, 1), Vector2f(2, 3)); // random Vector2f in ([0, 2], [1, 3))
Template Parameters
T The random number type to be generated
Parameters
[in] min The lower bound of the random number
[in] max The upper bound of the random number
Definition at line 199 of file random-inl.h.
References momentum::detail::generateUniform().
uniform() [2/4]
template<typename Generator > template<typename DynamicMatrix > DynamicMatrix momentum::Random< Generator >::uniform (Eigen::Index rows, Eigen::Index cols, typename DynamicMatrix::Scalar min, typename DynamicMatrix::Scalar max)
Generates a random matrix from the uniform distribution, where the size is dynamic.
This is a special case of T uniform(const T&, const T&) where the random number type is dynamic size of matrix and the bounds are specified by the scalar type.
Random rand;
auto r0 = rand.uniform<MatrixXf>(2, 3, 0, 1); // random MatrixXf of dimension 2x3 where each
element is in [0, 1)
Template Parameters
DynamicMatrix The random matrix type to be generated
Parameters
[in] rows The row size of the matrix.
[in] cols The column size of the matrix.
[in] min The lower bound in scalar.
[in] max The upper bound in scalar.
Definition at line 224 of file random-inl.h.
References momentum::detail::generateMatrixUniform().
uniform() [3/4]
template<typename Generator > template<typename DynamicVector > DynamicVector momentum::Random< Generator >::uniform (Eigen::Index size, typename DynamicVector::Scalar min, typename DynamicVector::Scalar max)
Generates a random vector from the uniform distribution, where the size is dynamic.
This is a special case of T uniform(const T&, const T&) where the random number type is dynamic size of vector and the bounds are specified by the scalar type.
Random rand;
auto r0 = rand.uniform<VectorXf>(2, 0, 1); // random VectorXf of dimension 2 where each
element is in [0, 1)
Template Parameters
DynamicVector The random vector type to be generated
Parameters
[in] size The size of the vector.
[in] min The lower bound in scalar.
[in] max The upper bound in scalar.
Definition at line 214 of file random-inl.h.
References momentum::detail::generateMatrixUniform().
uniform() [4/4]
template<typename Generator > template<typename FixedSizeT > FixedSizeT momentum::Random< Generator >::uniform (typename FixedSizeT::Scalar min, typename FixedSizeT::Scalar max)
Generates a random vector/matrix from the uniform distribution, where the size is fixed.
This is a special case of T uniform(const T&, const T&) where the random number type is fixed size of vector/matrix and the bounds are specified by the scalar type.
Random rand;
auto r0 = rand.uniform<Vector2f>(0, 1); // random Vector2f in ([0, 1], [0, 1))
Template Parameters
FixedSizeT The random vector/matrix type to be generated
Parameters
[in] min The lower bound in scalar.
[in] max The upper bound in scalar.
Definition at line 205 of file random-inl.h.
References momentum::detail::generateMatrixUniform().
uniformAffine3()
template<typename Generator > template<typename T > Affine3< T > momentum::Random< Generator >::uniformAffine3 (T scaleMin = 0.1, T scaleMax = 10.0, const Vector3< T > & min = Vector3<T>::Zero(), const Vector3< T > & max = Vector3<T>::Ones())
Generates a random affine transformation from a uniform distribution on the space of all affine transformations.
The transformation is created based on input minimum and maximum 3D vectors for the translation part, and minimum and maximum scale factors for the linear part.
Template Parameters
Generator The type of random number generator.
T The type of affine transformation component, typically a float or double.
Parameters
scaleMin The minimum scale factor for the linear part.
scaleMax The maximum scale factor for the linear part.
min The minimum 3D vector for the translation part.
max The maximum 3D vector for the translation part.
Returns
A random Affine3 of type T.
Definition at line 258 of file random-inl.h.
uniformIsometry3()
template<typename Generator > template<typename T > Isometry3< T > momentum::Random< Generator >::uniformIsometry3 (const Vector3< T > & min = Vector3<T>::Zero(), const Vector3< T > & max = Vector3<T>::Ones())
Generates a random isometry (rigid transformation) from a uniform distribution on SE(3) based on input minimum and maximum 3D vectors for the translation part.
Template Parameters
Generator The type of random number generator.
T The type of isometry component, typically a float or double.
Parameters
min The minimum 3D vector for the translation part.
max The maximum 3D vector for the translation part.
Returns
A random Isometry3 of type T.
Definition at line 249 of file random-inl.h.
uniformQuaternion()
template<typename Generator > template<typename T > Quaternion< T > momentum::Random< Generator >::uniformQuaternion ()
Generates a random quaternion from a uniform distribution on SO(3)
Definition at line 237 of file random-inl.h.
uniformRotationMatrix()
template<typename Generator > template<typename T > Matrix3< T > momentum::Random< Generator >::uniformRotationMatrix ()
Generates a random rotation matrix from a uniform distribution on SO(3)
Definition at line 243 of file random-inl.h.
The documentation for this class was generated from the following files:
math/random.h
math/random-inl.h