Momentum: momentum::SimdPlaneErrorFunction Class Reference
momentum::SimdPlaneErrorFunction Class Reference
A highly optimized error function for "point-on-plane" or "point-in-half-plane" errors.
#include <simd_plane_error_function.h>
Public Member Functions
SimdPlaneErrorFunction (const Skeleton &skel, const ParameterTransform &pt, uint32_t maxThreads=std::numeric_limits< uint32_t >::max())
SimdPlaneErrorFunction (const Character &character, uint32_t maxThreads=std::numeric_limits< uint32_t >::max())
double getError (const ModelParameters &params, const SkeletonState &state, const MeshState &) override
double getGradient (const ModelParameters &params, const SkeletonState &state, const MeshState &, Ref< VectorXf > gradient) override
double getJacobian (const ModelParameters &params, const SkeletonState &state, const MeshState &, Ref< MatrixXf > jacobian, Ref< VectorXf > residual, int &usedRows) override
size_t getJacobianSize () const override
void setConstraints (const SimdPlaneConstraints *cstrs)
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getError (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Attributes
std::vector< size_t > jacobianOffset_
const SimdPlaneConstraints * constraints_
uint32_t maxThreads_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr float kPlaneWeight = 1e-4f
Detailed Description
A highly optimized error function for "point-on-plane" or "point-in-half-plane" errors.
This function is recommended for use only when dealing with a large number of constraints. For a smaller number of constraints, consider using the generic PlaneErrorFunction.
Warning
Due to the multi-threaded evaluation of the error/gradient, the functions are non-deterministic. This might lead to numerical inconsistencies, resulting in slightly different outcomes on multiple calls with the same data.
Definition at line 70 of file simd_plane_error_function.h.
Constructor & Destructor Documentation
SimdPlaneErrorFunction() [1/2]
momentum::SimdPlaneErrorFunction::SimdPlaneErrorFunction (const Skeleton & skel, const ParameterTransform & pt, uint32_t maxThreads = std::numeric_limits<uint32_t>::max()) explicit
Parameters
maxThreads An optional parameter that specifies the maximum number of threads to be used with dispenso::parallel_for. If this parameter is set to zero, the function will run in serial mode, i.e., it will not use any additional threads. By default, the value is set to the maximum allowable size of a uint32_t, which is also the default for dispenso.
Definition at line 94 of file simd_plane_error_function.cpp.
References constraints_.
SimdPlaneErrorFunction() [2/2]
momentum::SimdPlaneErrorFunction::SimdPlaneErrorFunction (const Character & character, uint32_t maxThreads = std::numeric_limits<uint32_t>::max()) explicit
Parameters
maxThreads An optional parameter that specifies the maximum number of threads to be used with dispenso::parallel_for. If this parameter is set to zero, the function will run in serial mode, i.e., it will not use any additional threads. By default, the value is set to the maximum allowable size of a uint32_t, which is also the default for dispenso.
Definition at line 102 of file simd_plane_error_function.cpp.
Member Function Documentation
getError()
double momentum::SimdPlaneErrorFunction::getError (const ModelParameters & params, const SkeletonState & state, const MeshState &) override
Definition at line 107 of file simd_plane_error_function.cpp.
References momentum::SimdPlaneConstraints::constraintCount, constraints_, momentum::dot(), momentum::SimdPlaneConstraints::kMaxConstraints, kPlaneWeight, momentum::kSimdPacketSize, MT_CHECK, momentum::normal(), momentum::SimdPlaneConstraints::normalX, momentum::SimdPlaneConstraints::normalY, momentum::SimdPlaneConstraints::normalZ, momentum::SimdPlaneConstraints::numJoints, momentum::SimdPlaneConstraints::offsetX, momentum::SimdPlaneConstraints::offsetY, momentum::SimdPlaneConstraints::offsetZ, momentum::operator*(), momentum::SimdPlaneConstraints::targets, momentum::SkeletonErrorFunctionT< T >::weight_, and momentum::SimdPlaneConstraints::weights.
getGradient()
double momentum::SimdPlaneErrorFunction::getGradient (const ModelParameters & params, const SkeletonState & state, const MeshState & , Ref< VectorXf > gradient) override
Definition at line 156 of file simd_plane_error_function.cpp.
References constraints_, maxThreads_, and momentum::SimdPlaneConstraints::numJoints.
getJacobian()
double momentum::SimdPlaneErrorFunction::getJacobian (const ModelParameters & params, const SkeletonState & state, const MeshState & , Ref< MatrixXf > jacobian, Ref< VectorXf > residual, int & usedRows) override
Definition at line 301 of file simd_plane_error_function.cpp.
References MT_CHECK, and MT_PROFILE_FUNCTION.
getJacobianSize()
size_t momentum::SimdPlaneErrorFunction::getJacobianSize () const override virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 431 of file simd_plane_error_function.cpp.
References momentum::kSimdPacketSize.
setConstraints()
void momentum::SimdPlaneErrorFunction::setConstraints (const SimdPlaneConstraints * cstrs)
Definition at line 447 of file simd_plane_error_function.cpp.
Member Data Documentation
constraints_
const SimdPlaneConstraints* momentum::SimdPlaneErrorFunction::constraints_ protected
Definition at line 119 of file simd_plane_error_function.h.
Referenced by getError(), getGradient(), and SimdPlaneErrorFunction().
jacobianOffset_
std::vector<size_t> momentum::SimdPlaneErrorFunction::jacobianOffset_ mutable protected
Definition at line 116 of file simd_plane_error_function.h.
kPlaneWeight
constexpr float momentum::SimdPlaneErrorFunction::kPlaneWeight = 1e-4f static constexpr protected
Definition at line 114 of file simd_plane_error_function.h.
Referenced by getError().
maxThreads_
uint32_t momentum::SimdPlaneErrorFunction::maxThreads_ protected
Definition at line 121 of file simd_plane_error_function.h.
Referenced by getGradient().
The documentation for this class was generated from the following files:
character_solver/simd_plane_error_function.h
character_solver/simd_plane_error_function.cpp