Momentum: momentum::PoseTransformSolverT< T > Class Template Reference
momentum::PoseTransformSolverT< T > Class Template Reference
Solver which can be reused to repeatedly apply the transformPose function listed above.
#include <transform_pose.h>
Public Member Functions
PoseTransformSolverT (const Character &character)
~PoseTransformSolverT ()
void transformPose (ModelParametersT< T > &modelParameters, const TransformT< T > &transform, const ModelParametersT< T > &modelParametersPrev=ModelParametersT< T >{})
Applies a rigid transform to the given model parameters.
Detailed Description
template<typename T>
class momentum::PoseTransformSolverT< T >
Solver which can be reused to repeatedly apply the transformPose function listed above.
Definition at line 44 of file transform_pose.h.
Constructor & Destructor Documentation
PoseTransformSolverT()
template<typename T > momentum::PoseTransformSolverT< T >::PoseTransformSolverT (const Character & character) explicit
Definition at line 86 of file transform_pose.cpp.
References momentum::ParameterTransformT< T >::getParameterIdByName(), momentum::kInvalidIndex, momentum::SolverOptions::maxIterations, MT_CHECK, momentum::ParameterTransformT< T >::numAllModelParameters(), momentum::CharacterT< T >::parameterTransform, and momentum::EigenStrongType< ModelParametersT, ::Eigen::VectorX< T > >::Zero().
~PoseTransformSolverT()
template<typename T > momentum::PoseTransformSolverT< T >::~PoseTransformSolverT () default
Member Function Documentation
transformPose()
template<typename T > void momentum::PoseTransformSolverT< T >::transformPose (ModelParametersT< T > & modelParameters, const TransformT< T > & transform, const ModelParametersT< T > & modelParametersPrev = ModelParametersT<T>{})
Applies a rigid transform to the given model parameters.
Parameters
[in,out] modelParameters The model parameters to be transformed.
[in] transform The transform to apply.
[in] modelParametersPrev The previous pose, which is used to ensure continuity (the solver will initialize using the previous frame's rigid parameters).
Definition at line 134 of file transform_pose.cpp.
References MT_CHECK, MT_LOGW, and momentum::pi().
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/transform_pose.h
character_solver/transform_pose.cpp