Momentum: momentum::PointTriangleVertexErrorFunctionT< T > Class Template Reference
momentum::PointTriangleVertexErrorFunctionT< T > Class Template Reference
Support constraining different parts of the mesh together by specifying that a source vertex should target a location on the mesh defined by a target triangle and its normal.
#include <point_triangle_vertex_error_function.h>
Public Member Functions
PointTriangleVertexErrorFunctionT (const Character &character, VertexConstraintType type=VertexConstraintType::Position)
virtual ~PointTriangleVertexErrorFunctionT () override
double getError (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final
double getJacobian (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
void addConstraint (int vertexIndex, const Eigen::Vector3i &triangleIndices, const Eigen::Vector3< T > &triangleBaryCoords, float depth=0, T weight=1)
void clearConstraints ()
const std::vector< PointTriangleVertexConstraintT< T > > & getConstraints () const
size_t getNumVertices () const
const Character * getCharacter () const override
For mesh-based error functions, get access to the underlying character.
bool needsMesh () const override
Override to indicate this function requires mesh state.
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
Static Public Attributes
static constexpr T kPositionWeight = PositionErrorFunctionT<T>::kLegacyWeight
static constexpr T kPlaneWeight = PlaneErrorFunctionT<T>::kLegacyWeight
Additional Inherited Members
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Detailed Description
template<typename T>
class momentum::PointTriangleVertexErrorFunctionT< T >
Support constraining different parts of the mesh together by specifying that a source vertex should target a location on the mesh defined by a target triangle and its normal.
The target point is specified as sum_i (bary_i * target_triangle_vertex_i) + depth * target_triangle_normal. Note that this constraint applies "forces" both to the source vertex and every vertex in the target triangle, so it will actually try to pull both toward each other.
Definition at line 44 of file point_triangle_vertex_error_function.h.
Constructor & Destructor Documentation
PointTriangleVertexErrorFunctionT()
template<typename T > momentum::PointTriangleVertexErrorFunctionT< T >::PointTriangleVertexErrorFunctionT (const Character & character, VertexConstraintType type = VertexConstraintType::Position) explicit
Definition at line 30 of file point_triangle_vertex_error_function.cpp.
References MT_CHECK, MT_THROW_IF, momentum::Position, and momentum::toString().
~PointTriangleVertexErrorFunctionT()
template<typename T > momentum::PointTriangleVertexErrorFunctionT< T >::~PointTriangleVertexErrorFunctionT () override virtual default
Member Function Documentation
addConstraint()
template<typename T > void momentum::PointTriangleVertexErrorFunctionT< T >::addConstraint (int vertexIndex, const Eigen::Vector3i & triangleIndices, const Eigen::Vector3< T > & triangleBaryCoords, float depth = 0, T weight = 1)
Definition at line 58 of file point_triangle_vertex_error_function.cpp.
References MT_CHECK.
clearConstraints()
template<typename T > void momentum::PointTriangleVertexErrorFunctionT< T >::clearConstraints ()
Definition at line 53 of file point_triangle_vertex_error_function.cpp.
getCharacter()
template<typename T > const Character * momentum::PointTriangleVertexErrorFunctionT< T >::getCharacter () const inline override virtual
For mesh-based error functions, get access to the underlying character.
Error functions that depend only on the skeleton can return nullptr.
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 88 of file point_triangle_vertex_error_function.h.
getConstraints()
template<typename T > const std::vector< PointTriangleVertexConstraintT< T > > & momentum::PointTriangleVertexErrorFunctionT< T >::getConstraints () const inline
Definition at line 80 of file point_triangle_vertex_error_function.h.
getError()
template<typename T > double momentum::PointTriangleVertexErrorFunctionT< T >::getError (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 96 of file point_triangle_vertex_error_function.cpp.
References momentum::computeTargetBaryPosition(), momentum::computeTargetPosition(), momentum::computeTargetTriangleNormal(), momentum::kPositionWeight, MT_CHECK_NOTNULL, MT_PROFILE_FUNCTION, momentum::normal(), momentum::MeshStateT< T >::posedMesh_, and momentum::Position.
getGradient()
template<typename T > double momentum::PointTriangleVertexErrorFunctionT< T >::getGradient (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 836 of file point_triangle_vertex_error_function.cpp.
References MT_CHECK_NOTNULL, momentum::MeshStateT< T >::posedMesh_, and momentum::Position.
getJacobian()
template<typename T > double momentum::PointTriangleVertexErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 871 of file point_triangle_vertex_error_function.cpp.
References MT_CHECK, MT_CHECK_NOTNULL, MT_PROFILE_EVENT, momentum::MeshStateT< T >::posedMesh_, and momentum::Position.
getJacobianSize()
template<typename T > size_t momentum::PointTriangleVertexErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 925 of file point_triangle_vertex_error_function.cpp.
References momentum::Normal, momentum::Plane, momentum::Position, and momentum::SymmetricNormal.
getNumVertices()
template<typename T > size_t momentum::PointTriangleVertexErrorFunctionT< T >::getNumVertices () const
Definition at line 45 of file point_triangle_vertex_error_function.cpp.
needsMesh()
template<typename T > bool momentum::PointTriangleVertexErrorFunctionT< T >::needsMesh () const inline override virtual
Override to indicate this function requires mesh state.
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 93 of file point_triangle_vertex_error_function.h.
Member Data Documentation
kPlaneWeight
template<typename T > constexpr T momentum::PointTriangleVertexErrorFunctionT< T >::kPlaneWeight = PlaneErrorFunctionT<T>::kLegacyWeight static constexpr
Definition at line 85 of file point_triangle_vertex_error_function.h.
kPositionWeight
template<typename T > constexpr T momentum::PointTriangleVertexErrorFunctionT< T >::kPositionWeight = PositionErrorFunctionT<T>::kLegacyWeight static constexpr
Definition at line 84 of file point_triangle_vertex_error_function.h.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/point_triangle_vertex_error_function.h
character_solver/point_triangle_vertex_error_function.cpp