Momentum: momentum::CollisionErrorFunctionT< T > Class Template Reference
momentum::CollisionErrorFunctionT< T > Class Template Reference
#include <collision_error_function.h>
Classes
struct PairEqual
struct PairHash
Public Member Functions
CollisionErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const CollisionGeometry &cg)
CollisionErrorFunctionT (const Character &character)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< VectorX< T > > gradient) override
double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int &usedRows) override
size_t getJacobianSize () const final
std::vector< Vector2i > getCollisionPairs () const
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Types
using PairId = std::pair< size_t, size_t >
Protected Member Functions
void updateCollisionPairs ()
void computeBroadPhase (const SkeletonStateT< T > &state)
Protected Attributes
const CollisionGeometry collisionGeometry_
std::unordered_set< PairId, PairHash, PairEqual > excludingPairIds_
size_t jacobianSize_ = 0
CollisionGeometryStateT< T > collisionState_
axel::Bvh< T > bvh_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kCollisionWeight = 5e-3f
Detailed Description
template<typename T>
class momentum::CollisionErrorFunctionT< T >
Definition at line 23 of file collision_error_function.h.
Member Typedef Documentation
PairId
template<typename T > using momentum::CollisionErrorFunctionT< T >::PairId = std::pair<size_t, size_t> protected
Definition at line 61 of file collision_error_function.h.
Constructor & Destructor Documentation
CollisionErrorFunctionT() [1/2]
template<typename T > momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const CollisionGeometry & cg) explicit
Definition at line 20 of file collision_error_function.cpp.
References momentum::CollisionErrorFunctionT< T >::updateCollisionPairs().
CollisionErrorFunctionT() [2/2]
template<typename T > momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT (const Character & character) explicit
Definition at line 29 of file collision_error_function.cpp.
Member Function Documentation
computeBroadPhase()
template<typename T > void momentum::CollisionErrorFunctionT< T >::computeBroadPhase (const SkeletonStateT< T > & state) protected
Definition at line 126 of file collision_error_function.cpp.
References MT_PROFILE_EVENT, and momentum::updateAabb().
getCollisionPairs()
template<typename T > std::vector< Vector2i > momentum::CollisionErrorFunctionT< T >::getCollisionPairs () const
Definition at line 148 of file collision_error_function.cpp.
References distance, and momentum::overlaps().
getError()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 187 of file collision_error_function.cpp.
References distance, momentum::kParametersPerJoint, MT_CHECK, momentum::overlaps(), and momentum::sqr().
getGradient()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< VectorX< T > > gradient) override
Definition at line 240 of file collision_error_function.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, momentum::overlaps(), and momentum::sqr().
getJacobian()
template<typename T > double momentum::CollisionErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & , const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int & usedRows) override
Definition at line 419 of file collision_error_function.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, MT_CHECK, MT_PROFILE_FUNCTION, momentum::overlaps(), and momentum::sqr().
getJacobianSize()
template<typename T > size_t momentum::CollisionErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 620 of file collision_error_function.cpp.
updateCollisionPairs()
template<typename T > void momentum::CollisionErrorFunctionT< T >::updateCollisionPairs () protected
Definition at line 41 of file collision_error_function.cpp.
References distance, momentum::overlaps(), and momentum::updateAabb().
Referenced by momentum::CollisionErrorFunctionT< T >::CollisionErrorFunctionT().
Member Data Documentation
bvh_
template<typename T > axel::Bvh<T> momentum::CollisionErrorFunctionT< T >::bvh_ protected
Definition at line 89 of file collision_error_function.h.
collisionGeometry_
template<typename T > const CollisionGeometry momentum::CollisionErrorFunctionT< T >::collisionGeometry_ protected
Definition at line 78 of file collision_error_function.h.
collisionState_
template<typename T > CollisionGeometryStateT<T> momentum::CollisionErrorFunctionT< T >::collisionState_ protected
Definition at line 84 of file collision_error_function.h.
excludingPairIds_
template<typename T > std::unordered_set<PairId, PairHash, PairEqual> momentum::CollisionErrorFunctionT< T >::excludingPairIds_ protected
Definition at line 80 of file collision_error_function.h.
jacobianSize_
template<typename T > size_t momentum::CollisionErrorFunctionT< T >::jacobianSize_ = 0 protected
Definition at line 82 of file collision_error_function.h.
kCollisionWeight
template<typename T > constexpr T momentum::CollisionErrorFunctionT< T >::kCollisionWeight = 5e-3f static constexpr protected
Definition at line 87 of file collision_error_function.h.
The documentation for this class was generated from the following files:
character_solver/collision_error_function.h
character_solver/collision_error_function.cpp