Momentum: momentum::SkinnedLocatorTriangleErrorFunctionT< T > Class Template Reference
momentum::SkinnedLocatorTriangleErrorFunctionT< T > Class Template Reference
Support constraining a skinned locator to a location on the mesh defined by a target triangle and its normal.
#include <skinned_locator_triangle_error_function.h>
Public Member Functions
SkinnedLocatorTriangleErrorFunctionT (const Character &character, VertexConstraintType type=VertexConstraintType::Position)
~SkinnedLocatorTriangleErrorFunctionT () override
SkinnedLocatorTriangleErrorFunctionT (const SkinnedLocatorTriangleErrorFunctionT &other)=delete
SkinnedLocatorTriangleErrorFunctionT & operator= (const SkinnedLocatorTriangleErrorFunctionT &)=delete
SkinnedLocatorTriangleErrorFunctionT (SkinnedLocatorTriangleErrorFunctionT &&)=delete
SkinnedLocatorTriangleErrorFunctionT & operator= (SkinnedLocatorTriangleErrorFunctionT &&)=delete
double getError (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final
double getJacobian (const ModelParametersT< T > &modelParameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
void addConstraint (int locatorIndex, const Eigen::Vector3i &triangleIndices, const Eigen::Vector3< T > &triangleBaryCoords, float depth=0, T weight=1)
void clearConstraints ()
void setConstraints (const std::vector< SkinnedLocatorTriangleConstraintT< T > > &constraints)
const std::vector< SkinnedLocatorTriangleConstraintT< T > > & getConstraints () const
const Character * getCharacter () const override
For mesh-based error functions, get access to the underlying character.
bool needsMesh () const override
Override to indicate this function requires mesh state.
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
Additional Inherited Members
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Detailed Description
template<typename T>
class momentum::SkinnedLocatorTriangleErrorFunctionT< T >
Support constraining a skinned locator to a location on the mesh defined by a target triangle and its normal.
The target point is specified as sum_i (bary_i * target_triangle_vertex_i) + depth * target_triangle_normal. This constraint applies "forces" both to the skinned locator and every vertex in the mesh target triangle, so it will actually try to pull both toward each other.
Definition at line 44 of file skinned_locator_triangle_error_function.h.
Constructor & Destructor Documentation
SkinnedLocatorTriangleErrorFunctionT() [1/3]
template<typename T > momentum::SkinnedLocatorTriangleErrorFunctionT< T >::SkinnedLocatorTriangleErrorFunctionT (const Character & character, VertexConstraintType type = VertexConstraintType::Position) explicit
Definition at line 27 of file skinned_locator_triangle_error_function.cpp.
References MT_CHECK, MT_THROW_IF, momentum::Plane, and momentum::Position.
~SkinnedLocatorTriangleErrorFunctionT()
template<typename T > momentum::SkinnedLocatorTriangleErrorFunctionT< T >::~SkinnedLocatorTriangleErrorFunctionT () override default
SkinnedLocatorTriangleErrorFunctionT() [2/3]
template<typename T > momentum::SkinnedLocatorTriangleErrorFunctionT< T >::SkinnedLocatorTriangleErrorFunctionT (const SkinnedLocatorTriangleErrorFunctionT< T > & other) delete
SkinnedLocatorTriangleErrorFunctionT() [3/3]
template<typename T > momentum::SkinnedLocatorTriangleErrorFunctionT< T >::SkinnedLocatorTriangleErrorFunctionT (SkinnedLocatorTriangleErrorFunctionT< T > &&) delete
Member Function Documentation
addConstraint()
template<typename T > void momentum::SkinnedLocatorTriangleErrorFunctionT< T >::addConstraint (int locatorIndex, const Eigen::Vector3i & triangleIndices, const Eigen::Vector3< T > & triangleBaryCoords, float depth = 0, T weight = 1)
Definition at line 54 of file skinned_locator_triangle_error_function.cpp.
References MT_CHECK.
clearConstraints()
template<typename T > void momentum::SkinnedLocatorTriangleErrorFunctionT< T >::clearConstraints ()
Definition at line 43 of file skinned_locator_triangle_error_function.cpp.
getCharacter()
template<typename T > const Character * momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getCharacter () const inline override virtual
For mesh-based error functions, get access to the underlying character.
Error functions that depend only on the skeleton can return nullptr.
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 91 of file skinned_locator_triangle_error_function.h.
getConstraints()
template<typename T > const std::vector< SkinnedLocatorTriangleConstraintT< T > > & momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getConstraints () const inline
Definition at line 87 of file skinned_locator_triangle_error_function.h.
getError()
template<typename T > double momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getError (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 160 of file skinned_locator_triangle_error_function.cpp.
References momentum::computeTargetBaryPosition(), momentum::computeTargetPosition(), momentum::computeTargetTriangleNormal(), MT_CHECK, MT_CHECK_NOTNULL, MT_PROFILE_FUNCTION, momentum::Plane, momentum::Position, and momentum::MeshStateT< T >::restMesh_.
getGradient()
template<typename T > double momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getGradient (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::VectorX< T > > gradient) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 461 of file skinned_locator_triangle_error_function.cpp.
References MT_CHECK, MT_CHECK_NOTNULL, momentum::Plane, momentum::Position, and momentum::MeshStateT< T >::restMesh_.
getJacobian()
template<typename T > double momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & modelParameters, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 485 of file skinned_locator_triangle_error_function.cpp.
References MT_CHECK, momentum::Plane, momentum::Position, and momentum::MeshStateT< T >::restMesh_.
getJacobianSize()
template<typename T > size_t momentum::SkinnedLocatorTriangleErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 531 of file skinned_locator_triangle_error_function.cpp.
References momentum::Plane, and momentum::Position.
needsMesh()
template<typename T > bool momentum::SkinnedLocatorTriangleErrorFunctionT< T >::needsMesh () const inline override virtual
Override to indicate this function requires mesh state.
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 96 of file skinned_locator_triangle_error_function.h.
operator=() [1/2]
template<typename T > SkinnedLocatorTriangleErrorFunctionT & momentum::SkinnedLocatorTriangleErrorFunctionT< T >::operator= (const SkinnedLocatorTriangleErrorFunctionT< T > &) delete
operator=() [2/2]
template<typename T > SkinnedLocatorTriangleErrorFunctionT & momentum::SkinnedLocatorTriangleErrorFunctionT< T >::operator= (SkinnedLocatorTriangleErrorFunctionT< T > &&) delete
setConstraints()
template<typename T > void momentum::SkinnedLocatorTriangleErrorFunctionT< T >::setConstraints (const std::vector< SkinnedLocatorTriangleConstraintT< T > > & constraints)
Definition at line 48 of file skinned_locator_triangle_error_function.cpp.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/skinned_locator_triangle_error_function.h
character_solver/skinned_locator_triangle_error_function.cpp