Momentum: momentum::LimitErrorFunctionT< T > Class Template Reference
momentum::LimitErrorFunctionT< T > Class Template Reference
#include <limit_error_function.h>
Public Member Functions
LimitErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const ParameterLimits &pl=ParameterLimits())
LimitErrorFunctionT (const Character &character)
LimitErrorFunctionT (const Character &character, const ParameterLimits &pl)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< Eigen::VectorX< T > > gradient) final
double getJacobian (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, Ref< Eigen::MatrixX< T > > jacobian, Ref< Eigen::VectorX< T > > residual, int &usedRows) final
size_t getJacobianSize () const final
void setLimits (const ParameterLimits &lm)
void setLimits (const Character &character)
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Additional Inherited Members
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Detailed Description
template<typename T>
class momentum::LimitErrorFunctionT< T >
Definition at line 18 of file limit_error_function.h.
Constructor & Destructor Documentation
LimitErrorFunctionT() [1/3]
template<typename T > momentum::LimitErrorFunctionT< T >::LimitErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const ParameterLimits & pl = ParameterLimits())
Definition at line 21 of file limit_error_function.cpp.
LimitErrorFunctionT() [2/3]
template<typename T > momentum::LimitErrorFunctionT< T >::LimitErrorFunctionT (const Character & character) explicit
Definition at line 28 of file limit_error_function.cpp.
LimitErrorFunctionT() [3/3]
template<typename T > momentum::LimitErrorFunctionT< T >::LimitErrorFunctionT (const Character & character, const ParameterLimits & pl)
Definition at line 35 of file limit_error_function.cpp.
Member Function Documentation
getError()
template<typename T > double momentum::LimitErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 39 of file limit_error_function.cpp.
References momentum::Ellipsoid, momentum::HalfPlane, momentum::isInRange(), momentum::kParametersPerJoint, momentum::kPositionWeight, momentum::Linear, momentum::LinearJoint, momentum::MinMax, momentum::MinMaxJoint, momentum::MinMaxJointPassive, MT_CHECK, MT_PROFILE_FUNCTION, and MT_THROW.
getGradient()
template<typename T > double momentum::LimitErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< Eigen::VectorX< T > > gradient) final
Definition at line 181 of file limit_error_function.cpp.
References momentum::Ellipsoid, momentum::HalfPlane, momentum::isInRange(), momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, momentum::Linear, momentum::LinearJoint, momentum::MinMax, momentum::MinMaxJoint, momentum::MinMaxJointPassive, MT_CHECK, MT_PROFILE_FUNCTION, MT_THROW, parameterTransform, and momentum::ParameterTransformT< T >::transform.
getJacobian()
template<typename T > double momentum::LimitErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & meshState, Ref< Eigen::MatrixX< T > > jacobian, Ref< Eigen::VectorX< T > > residual, int & usedRows) final
Definition at line 425 of file limit_error_function.cpp.
References momentum::Ellipsoid, momentum::HalfPlane, momentum::isInRange(), momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, momentum::Linear, momentum::LinearJoint, momentum::MinMax, momentum::MinMaxJoint, momentum::MinMaxJointPassive, MT_CHECK, MT_PROFILE_FUNCTION, MT_THROW, parameterTransform, and momentum::ParameterTransformT< T >::transform.
getJacobianSize()
template<typename T > size_t momentum::LimitErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 699 of file limit_error_function.cpp.
References momentum::Ellipsoid, momentum::HalfPlane, momentum::Linear, momentum::LinearJoint, momentum::MinMax, momentum::MinMaxJoint, momentum::MinMaxJointPassive, and MT_THROW.
setLimits() [1/2]
template<typename T > void momentum::LimitErrorFunctionT< T >::setLimits (const Character & character)
Definition at line 730 of file limit_error_function.cpp.
References momentum::CharacterT< T >::parameterLimits.
setLimits() [2/2]
template<typename T > void momentum::LimitErrorFunctionT< T >::setLimits (const ParameterLimits & lm)
Definition at line 725 of file limit_error_function.cpp.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/limit_error_function.h
character_solver/limit_error_function.cpp