Momentum: momentum::SequenceSolverT< T > Class Template Reference
momentum::SequenceSolverT< T > Class Template Reference
#include <sequence_solver.h>
Public Member Functions
SequenceSolverT (const SolverOptions &options, SequenceSolverFunctionT< T > *function)
std::string_view getName () const override
Returns the name of the solver implementation.
void setOptions (const SolverOptions &options) final
Updates solver configuration with new options.
void setEnabledParameters (const ParameterSet &parameters) final
Specifies which parameters should be optimized.
void iter ()
void init ()
Eigen::VectorX< T > getP ()
Public Member Functions inherited from momentum::SolverT< T >
SolverT (const SolverOptions &options, SolverFunctionT< T > *solver)
Constructor with solver options and function to optimize.
virtual ~SolverT ()=default
double solve (Eigen::VectorX< T > &params)
Solves the optimization problem.
const ParameterSet & getActiveParameters () const
Returns the current set of enabled parameters.
void setParameters (const Eigen::VectorX< T > &params)
Sets the current parameter values without solving.
void setStoreHistory (bool b)
Controls whether to store iteration history for debugging and analysis.
const std::unordered_map< std::string, Eigen::MatrixX< T > > & getHistory () const
Returns the history of the solver's iterations.
size_t getMinIterations () const
Returns the minimum number of iterations before checking convergence.
size_t getMaxIterations () const
Returns the maximum number of iterations before terminating.
size_t getNumParameters () const
const std::vector< double > & getErrorHistory () const
Returns the history of objective function values over the iterations of the solve.
Protected Member Functions
void doIteration () final
Performs a single iteration of the optimization algorithm.
void initializeSolver () final
Initializes solver state before optimization begins.
Additional Inherited Members
Protected Attributes inherited from momentum::SolverT< T >
size_t numParameters_
Total number of parameters in the optimization problem.
SolverFunctionT< T > * solverFunction_
Function to be optimized.
Eigen::VectorX< T > parameters_
Current parameter values.
ParameterSet activeParameters_
Bitset indicating which parameters are enabled for optimization.
int actualParameters_
Number of parameters currently enabled for optimization.
bool newParameterPattern_
Flag indicating parameter structure has changed.
size_t iteration_ {}
Current iteration count.
double error_ {}
Current objective function value.
double lastError_ {}
Previous iteration's objective function value.
bool storeHistory = false
Whether to record optimization progress for analysis.
std::unordered_map< std::string, Eigen::MatrixX< T > > iterationHistory_
Recorded data from optimization process.
std::vector< double > errorHistory_
History of objective function values over the iterations.
bool verbose_ = false
Whether to output detailed progress information.
Detailed Description
template<typename T>
class momentum::SequenceSolverT< T >
Definition at line 45 of file sequence_solver.h.
Constructor & Destructor Documentation
SequenceSolverT()
template<typename T > momentum::SequenceSolverT< T >::SequenceSolverT (const SolverOptions & options, SequenceSolverFunctionT< T > * function)
Definition at line 29 of file sequence_solver.cpp.
References momentum::SequenceSolverOptions::doLineSearch, momentum::SequenceSolverOptions::multithreaded, momentum::SequenceSolverOptions::progressBar, momentum::SequenceSolverOptions::regularization, and momentum::SequenceSolverT< T >::setOptions().
Member Function Documentation
doIteration()
template<typename T > void momentum::SequenceSolverT< T >::doIteration () final protected virtual
Performs a single iteration of the optimization algorithm.
Implements momentum::SolverT< T >.
Definition at line 544 of file sequence_solver.cpp.
References MT_CHECK, and MT_PROFILE_FUNCTION.
Referenced by momentum::SequenceSolverT< T >::iter().
getName()
template<typename T > std::string_view momentum::SequenceSolverT< T >::getName () const override virtual
Returns the name of the solver implementation.
Implements momentum::SolverT< T >.
Definition at line 44 of file sequence_solver.cpp.
getP()
template<typename T > Eigen::VectorX< T > momentum::SequenceSolverT< T >::getP () inline
Definition at line 73 of file sequence_solver.h.
References momentum::SolverT< T >::parameters_.
init()
template<typename T > void momentum::SequenceSolverT< T >::init () inline
Definition at line 68 of file sequence_solver.h.
References momentum::SequenceSolverT< T >::initializeSolver(), and momentum::SolverT< T >::iteration_.
initializeSolver()
template<typename T > void momentum::SequenceSolverT< T >::initializeSolver () final protected virtual
Initializes solver state before optimization begins.
Implements momentum::SolverT< T >.
Definition at line 61 of file sequence_solver.cpp.
References MT_CHECK, and MT_PROFILE_FUNCTION.
Referenced by momentum::SequenceSolverT< T >::init().
iter()
template<typename T > void momentum::SequenceSolverT< T >::iter () inline
Definition at line 63 of file sequence_solver.h.
References momentum::SequenceSolverT< T >::doIteration(), and momentum::SolverT< T >::iteration_.
setEnabledParameters()
template<typename T > void momentum::SequenceSolverT< T >::setEnabledParameters (const ParameterSet & parameters) inline final virtual
Specifies which parameters should be optimized.
Parameters
parameters Bitset where each bit indicates if the corresponding parameter is enabled
Reimplemented from momentum::SolverT< T >.
Definition at line 58 of file sequence_solver.h.
References momentum::SolverT< T >::numParameters_, momentum::SolverT< T >::setEnabledParameters(), and momentum::SolverT< T >::solverFunction_.
setOptions()
template<typename T > void momentum::SequenceSolverT< T >::setOptions (const SolverOptions & options) final virtual
Updates solver configuration with new options.
Reimplemented from momentum::SolverT< T >.
Definition at line 49 of file sequence_solver.cpp.
References momentum::SolverT< T >::setOptions().
Referenced by momentum::SequenceSolverT< T >::SequenceSolverT().
The documentation for this class was generated from the following files:
character_sequence_solver/fwd.h
character_sequence_solver/sequence_solver.h
character_sequence_solver/sequence_solver.cpp