Momentum: momentum::GradientDescentSolverT< T > Class Template Reference
momentum::GradientDescentSolverT< T > Class Template Reference
First-order optimization algorithm that follows the negative gradient.
#include <gradient_descent_solver.h>
Public Member Functions
GradientDescentSolverT (const SolverOptions &options, SolverFunctionT< T > *solver)
Creates a solver with the specified options and function to optimize.
std::string_view getName () const override
Returns "GradientDescent" as the solver name.
void setOptions (const SolverOptions &options) final
Updates solver configuration, handling both base and Gradient Descent specific options.
Public Member Functions inherited from momentum::SolverT< T >
SolverT (const SolverOptions &options, SolverFunctionT< T > *solver)
Constructor with solver options and function to optimize.
virtual ~SolverT ()=default
double solve (Eigen::VectorX< T > &params)
Solves the optimization problem.
virtual void setEnabledParameters (const ParameterSet &parameters)
Specifies which parameters should be optimized.
const ParameterSet & getActiveParameters () const
Returns the current set of enabled parameters.
void setParameters (const Eigen::VectorX< T > &params)
Sets the current parameter values without solving.
void setStoreHistory (bool b)
Controls whether to store iteration history for debugging and analysis.
const std::unordered_map< std::string, Eigen::MatrixX< T > > & getHistory () const
Returns the history of the solver's iterations.
size_t getMinIterations () const
Returns the minimum number of iterations before checking convergence.
size_t getMaxIterations () const
Returns the maximum number of iterations before terminating.
size_t getNumParameters () const
const std::vector< double > & getErrorHistory () const
Returns the history of objective function values over the iterations of the solve.
Protected Member Functions
void doIteration () final
Performs one iteration of the gradient descent algorithm.
void initializeSolver () final
Initializes solver state before optimization begins.
Additional Inherited Members
Protected Attributes inherited from momentum::SolverT< T >
size_t numParameters_
Total number of parameters in the optimization problem.
SolverFunctionT< T > * solverFunction_
Function to be optimized.
Eigen::VectorX< T > parameters_
Current parameter values.
ParameterSet activeParameters_
Bitset indicating which parameters are enabled for optimization.
int actualParameters_
Number of parameters currently enabled for optimization.
bool newParameterPattern_
Flag indicating parameter structure has changed.
size_t iteration_ {}
Current iteration count.
double error_ {}
Current objective function value.
double lastError_ {}
Previous iteration's objective function value.
bool storeHistory = false
Whether to record optimization progress for analysis.
std::unordered_map< std::string, Eigen::MatrixX< T > > iterationHistory_
Recorded data from optimization process.
std::vector< double > errorHistory_
History of objective function values over the iterations.
bool verbose_ = false
Whether to output detailed progress information.
Detailed Description
template<typename T>
class momentum::GradientDescentSolverT< T >
First-order optimization algorithm that follows the negative gradient.
Implements the standard gradient descent method which iteratively updates parameters by moving in the direction of steepest descent
Definition at line 37 of file gradient_descent_solver.h.
Constructor & Destructor Documentation
GradientDescentSolverT()
template<typename T > momentum::GradientDescentSolverT< T >::GradientDescentSolverT (const SolverOptions & options, SolverFunctionT< T > * solver)
Creates a solver with the specified options and function to optimize.
Definition at line 16 of file gradient_descent_solver.cpp.
References momentum::GradientDescentSolverOptions::learningRate, and momentum::GradientDescentSolverT< T >::setOptions().
Member Function Documentation
doIteration()
template<typename T > void momentum::GradientDescentSolverT< T >::doIteration () final protected virtual
Performs one iteration of the gradient descent algorithm.
Computes the gradient and updates parameters by moving in the negative gradient direction
Implements momentum::SolverT< T >.
Definition at line 45 of file gradient_descent_solver.cpp.
References MT_PROFILE_FUNCTION.
getName()
template<typename T > std::string_view momentum::GradientDescentSolverT< T >::getName () const override virtual
Returns "GradientDescent" as the solver name.
Implements momentum::SolverT< T >.
Definition at line 28 of file gradient_descent_solver.cpp.
initializeSolver()
template<typename T > void momentum::GradientDescentSolverT< T >::initializeSolver () final protected virtual
Initializes solver state before optimization begins.
Implements momentum::SolverT< T >.
Definition at line 42 of file gradient_descent_solver.cpp.
setOptions()
template<typename T > void momentum::GradientDescentSolverT< T >::setOptions (const SolverOptions & options) final virtual
Updates solver configuration, handling both base and Gradient Descent specific options.
Reimplemented from momentum::SolverT< T >.
Definition at line 33 of file gradient_descent_solver.cpp.
References momentum::SolverT< T >::setOptions().
Referenced by momentum::GradientDescentSolverT< T >::GradientDescentSolverT().
The documentation for this class was generated from the following files:
solver/fwd.h
solver/gradient_descent_solver.h
solver/gradient_descent_solver.cpp