Momentum: momentum::TrustRegionQRT< T > Class Template Reference
momentum::TrustRegionQRT< T > Class Template Reference
#include <trust_region_qr.h>
Public Member Functions
TrustRegionQRT (const SolverOptions &options, SkeletonSolverFunctionT< T > *solverFun)
std::string_view getName () const override
Returns the name of the solver implementation.
void setOptions (const SolverOptions &options) final
Updates solver configuration with new options.
void iter ()
void init ()
Eigen::VectorX< T > getP ()
Public Member Functions inherited from momentum::SolverT< T >
SolverT (const SolverOptions &options, SolverFunctionT< T > *solver)
Constructor with solver options and function to optimize.
virtual ~SolverT ()=default
double solve (Eigen::VectorX< T > &params)
Solves the optimization problem.
virtual void setEnabledParameters (const ParameterSet &parameters)
Specifies which parameters should be optimized.
const ParameterSet & getActiveParameters () const
Returns the current set of enabled parameters.
void setParameters (const Eigen::VectorX< T > &params)
Sets the current parameter values without solving.
void setStoreHistory (bool b)
Controls whether to store iteration history for debugging and analysis.
const std::unordered_map< std::string, Eigen::MatrixX< T > > & getHistory () const
Returns the history of the solver's iterations.
size_t getMinIterations () const
Returns the minimum number of iterations before checking convergence.
size_t getMaxIterations () const
Returns the maximum number of iterations before terminating.
size_t getNumParameters () const
const std::vector< double > & getErrorHistory () const
Returns the history of objective function values over the iterations of the solve.
Protected Member Functions
void doIteration () final
Performs a single iteration of the optimization algorithm.
void initializeSolver () final
Initializes solver state before optimization begins.
Additional Inherited Members
Protected Attributes inherited from momentum::SolverT< T >
size_t numParameters_
Total number of parameters in the optimization problem.
SolverFunctionT< T > * solverFunction_
Function to be optimized.
Eigen::VectorX< T > parameters_
Current parameter values.
ParameterSet activeParameters_
Bitset indicating which parameters are enabled for optimization.
int actualParameters_
Number of parameters currently enabled for optimization.
bool newParameterPattern_
Flag indicating parameter structure has changed.
size_t iteration_ {}
Current iteration count.
double error_ {}
Current objective function value.
double lastError_ {}
Previous iteration's objective function value.
bool storeHistory = false
Whether to record optimization progress for analysis.
std::unordered_map< std::string, Eigen::MatrixX< T > > iterationHistory_
Recorded data from optimization process.
std::vector< double > errorHistory_
History of objective function values over the iterations.
bool verbose_ = false
Whether to output detailed progress information.
Detailed Description
template<typename T>
class momentum::TrustRegionQRT< T >
Definition at line 35 of file trust_region_qr.h.
Constructor & Destructor Documentation
TrustRegionQRT()
template<typename T > momentum::TrustRegionQRT< T >::TrustRegionQRT (const SolverOptions & options, SkeletonSolverFunctionT< T > * solverFun)
Definition at line 20 of file trust_region_qr.cpp.
References momentum::TrustRegionQRT< T >::setOptions(), and momentum::TrustRegionQROptions::trustRegionRadius_.
Member Function Documentation
doIteration()
template<typename T > void momentum::TrustRegionQRT< T >::doIteration () final protected virtual
Performs a single iteration of the optimization algorithm.
Implements momentum::SolverT< T >.
Definition at line 51 of file trust_region_qr.cpp.
References momentum::ParameterTransformT< T >::apply(), MT_LOGI_IF, MT_PROFILE_EVENT, MT_PROFILE_FUNCTION, parameterTransform, and skeleton.
Referenced by momentum::TrustRegionQRT< T >::iter().
getName()
template<typename T > std::string_view momentum::TrustRegionQRT< T >::getName () const override virtual
Returns the name of the solver implementation.
Implements momentum::SolverT< T >.
Definition at line 32 of file trust_region_qr.cpp.
getP()
template<typename T > Eigen::VectorX< T > momentum::TrustRegionQRT< T >::getP () inline
Definition at line 53 of file trust_region_qr.h.
References momentum::SolverT< T >::parameters_.
init()
template<typename T > void momentum::TrustRegionQRT< T >::init () inline
Definition at line 48 of file trust_region_qr.h.
References momentum::TrustRegionQRT< T >::initializeSolver(), and momentum::SolverT< T >::iteration_.
initializeSolver()
template<typename T > void momentum::TrustRegionQRT< T >::initializeSolver () final protected virtual
Initializes solver state before optimization begins.
Implements momentum::SolverT< T >.
Definition at line 37 of file trust_region_qr.cpp.
Referenced by momentum::TrustRegionQRT< T >::init().
iter()
template<typename T > void momentum::TrustRegionQRT< T >::iter () inline
Definition at line 43 of file trust_region_qr.h.
References momentum::TrustRegionQRT< T >::doIteration(), and momentum::SolverT< T >::iteration_.
setOptions()
template<typename T > void momentum::TrustRegionQRT< T >::setOptions (const SolverOptions & options) final virtual
Updates solver configuration with new options.
Reimplemented from momentum::SolverT< T >.
Definition at line 42 of file trust_region_qr.cpp.
References momentum::SolverT< T >::setOptions().
Referenced by momentum::TrustRegionQRT< T >::TrustRegionQRT().
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/trust_region_qr.h
character_solver/trust_region_qr.cpp