Momentum: momentum::StateSequenceErrorFunctionT< T > Class Template Reference
momentum::StateSequenceErrorFunctionT< T > Class Template Reference
Error function that penalizes the difference between the current skeleton state and the next skeleton state.
#include <state_sequence_error_function.h>
Public Member Functions
StateSequenceErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, RotationErrorType rotationErrorType=RotationErrorType::RotationMatrixDifference)
StateSequenceErrorFunctionT (const Character &character, RotationErrorType rotationErrorType=RotationErrorType::RotationMatrixDifference)
size_t numFrames () const final
double getError (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > >) const final
double getGradient (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > >, Eigen::Ref< Eigen::VectorX< T > > gradient) const final
double getJacobian (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > >, Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int &usedRows) const final
size_t getJacobianSize () const final
void setTargetWeights (const Eigen::VectorX< T > &posWeight, const Eigen::VectorX< T > &rotWeight)
Set the target weights for each joint's position and rotation.
void setPositionTargetWeights (const Eigen::VectorX< T > &posWeight)
Set the target position weights for each joint.
void setRotationTargetWeights (const Eigen::VectorX< T > &rotWeight)
Set the target rotation weights for each joint.
void setWeights (const float posWeight, const float rotationWeight)
void reset ()
const Eigen::VectorX< T > & getPositionWeights () const
const Eigen::VectorX< T > & getRotationWeights () const
const T & getPositionWeight () const
const T & getRotationWeight () const
void setTargetState (TransformListT< T > target)
Set the target state for the skeleton.
Public Member Functions inherited from momentum::SequenceErrorFunctionT< T >
SequenceErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SequenceErrorFunctionT ()=default
void setWeight (T w)
float getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual bool needsMesh () const
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
Static Public Attributes
static constexpr T kPositionWeight = 1e-3f
static constexpr T kOrientationWeight = 1e+0f
Additional Inherited Members
Protected Attributes inherited from momentum::SequenceErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_ = 1.0f
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
Detailed Description
template<typename T>
class momentum::StateSequenceErrorFunctionT< T >
Error function that penalizes the difference between the current skeleton state and the next skeleton state.
Note that by default this penalizes any difference between adjacent skeleton states. If we specify a target state, this will be applied as an offset to the current state, that is, the error will penalize the difference between offset * currentState and nextState.
Definition at line 22 of file state_sequence_error_function.h.
Constructor & Destructor Documentation
StateSequenceErrorFunctionT() [1/2]
template<typename T > momentum::StateSequenceErrorFunctionT< T >::StateSequenceErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, RotationErrorType rotationErrorType = RotationErrorType::RotationMatrixDifference)
Definition at line 217 of file state_sequence_error_function.cpp.
References momentum::SkeletonT< T >::joints, and momentum::SequenceErrorFunctionT< T >::skeleton_.
StateSequenceErrorFunctionT() [2/2]
template<typename T > momentum::StateSequenceErrorFunctionT< T >::StateSequenceErrorFunctionT (const Character & character, RotationErrorType rotationErrorType = RotationErrorType::RotationMatrixDifference) explicit
Definition at line 229 of file state_sequence_error_function.cpp.
Member Function Documentation
getError()
template<typename T > double momentum::StateSequenceErrorFunctionT< T >::getError (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > >) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 270 of file state_sequence_error_function.cpp.
References momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), and momentum::RotationMatrixDifference.
getGradient()
template<typename T > double momentum::StateSequenceErrorFunctionT< T >::getGradient (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > , Eigen::Ref< Eigen::VectorX< T > > gradient) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 331 of file state_sequence_error_function.cpp.
References momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), momentum::quaternionLogMapDerivative(), and momentum::RotationMatrixDifference.
getJacobian()
template<typename T > double momentum::StateSequenceErrorFunctionT< T >::getJacobian (std::span< const ModelParametersT< T > > modelParameters, std::span< const SkeletonStateT< T > > skelStates, std::span< const MeshStateT< T > > , Eigen::Ref< Eigen::MatrixX< T > > jacobian, Eigen::Ref< Eigen::VectorX< T > > residual, int & usedRows) const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 539 of file state_sequence_error_function.cpp.
References momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kPositionWeight, MT_CHECK, MT_PROFILE_FUNCTION, momentum::QuaternionLogMap, momentum::quaternionLogMap(), momentum::quaternionLogMapDerivative(), and momentum::RotationMatrixDifference.
getJacobianSize()
template<typename T > size_t momentum::StateSequenceErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SequenceErrorFunctionT< T >.
Definition at line 526 of file state_sequence_error_function.cpp.
References momentum::QuaternionLogMap.
getPositionWeight()
template<typename T > const T & momentum::StateSequenceErrorFunctionT< T >::getPositionWeight () const inline
Definition at line 85 of file state_sequence_error_function.h.
getPositionWeights()
template<typename T > const Eigen::VectorX< T > & momentum::StateSequenceErrorFunctionT< T >::getPositionWeights () const inline
Definition at line 79 of file state_sequence_error_function.h.
getRotationWeight()
template<typename T > const T & momentum::StateSequenceErrorFunctionT< T >::getRotationWeight () const inline
Definition at line 88 of file state_sequence_error_function.h.
getRotationWeights()
template<typename T > const Eigen::VectorX< T > & momentum::StateSequenceErrorFunctionT< T >::getRotationWeights () const inline
Definition at line 82 of file state_sequence_error_function.h.
numFrames()
template<typename T > size_t momentum::StateSequenceErrorFunctionT< T >::numFrames () const inline final virtual
Implements momentum::SequenceErrorFunctionT< T >.
Definition at line 32 of file state_sequence_error_function.h.
reset()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::reset ()
Definition at line 238 of file state_sequence_error_function.cpp.
setPositionTargetWeights()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::setPositionTargetWeights (const Eigen::VectorX< T > & posWeight)
Set the target position weights for each joint.
Parameters
posWeight Per-joint position weights.
Definition at line 258 of file state_sequence_error_function.cpp.
References MT_CHECK.
setRotationTargetWeights()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::setRotationTargetWeights (const Eigen::VectorX< T > & rotWeight)
Set the target rotation weights for each joint.
Parameters
rotWeight Per-joint rotation weights.
Definition at line 264 of file state_sequence_error_function.cpp.
References MT_CHECK.
setTargetState()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::setTargetState (TransformListT< T > target)
Set the target state for the skeleton.
This function allows specifying a target state that the skeleton should aim to achieve. The target state is represented as a list of transforms, one for each joint. The error will penalize the difference between offset * currentState and nextState.
Parameters
target A list of transforms representing the target state for each joint.
Definition at line 244 of file state_sequence_error_function.cpp.
References MT_CHECK.
setTargetWeights()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::setTargetWeights (const Eigen::VectorX< T > & posWeight, const Eigen::VectorX< T > & rotWeight)
Set the target weights for each joint's position and rotation.
Parameters
posWeight Per-joint position weights.
rotWeight Per-joint rotation weights.
Definition at line 250 of file state_sequence_error_function.cpp.
setWeights()
template<typename T > void momentum::StateSequenceErrorFunctionT< T >::setWeights (const float posWeight, const float rotationWeight) inline
Definition at line 72 of file state_sequence_error_function.h.
Member Data Documentation
kOrientationWeight
template<typename T > constexpr T momentum::StateSequenceErrorFunctionT< T >::kOrientationWeight = 1e+0f static constexpr
Definition at line 114 of file state_sequence_error_function.h.
kPositionWeight
template<typename T > constexpr T momentum::StateSequenceErrorFunctionT< T >::kPositionWeight = 1e-3f static constexpr
Definition at line 113 of file state_sequence_error_function.h.
The documentation for this class was generated from the following files:
character_sequence_solver/fwd.h
character_sequence_solver/state_sequence_error_function.h
character_sequence_solver/state_sequence_error_function.cpp