Momentum: momentum::SimdCollisionErrorFunctionT< T > Class Template Reference
momentum::SimdCollisionErrorFunctionT< T > Class Template Reference
Represents an error function that penalizes self-intersections between collision geometries of the character.
#include <simd_collision_error_function.h>
Classes
struct PairEqual
struct PairHash
Public Member Functions
SimdCollisionErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt, const CollisionGeometry &collisionGeometry)
SimdCollisionErrorFunctionT (const Character &character)
double getError (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &) final
double getGradient (const ModelParametersT< T > &params, const SkeletonStateT< T > &state, const MeshStateT< T > &, Ref< VectorX< T > > gradient) override
double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &state, const MeshStateT< T > &, Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int &usedRows) override
size_t getJacobianSize () const final
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Types
using PairId = std::pair< size_t, size_t >
Protected Member Functions
void updateCollisionPairs ()
void computeBroadPhase (const SkeletonStateT< T > &state)
Protected Attributes
const CollisionGeometry collisionGeometry_
std::unordered_set< PairId, PairHash, PairEqual > excludingPairIds_
std::vector< std::vector< int, AlignedAllocator< int, momentum::kSimdAlignment > > > collisionPairs_
size_t jacobianSize_ = 0
CollisionGeometryStateT< T > collisionState_
axel::Bvh< T > bvh_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr T kCollisionWeight = 5e-3f
Detailed Description
template<typename T>
class momentum::SimdCollisionErrorFunctionT< T >
Represents an error function that penalizes self-intersections between collision geometries of the character.
The function pre-filters collision geometries to ignore those attached to the same joint, those intersecting in the rest pose, or those very close in the rest pose.
Definition at line 30 of file simd_collision_error_function.h.
Member Typedef Documentation
PairId
template<typename T > using momentum::SimdCollisionErrorFunctionT< T >::PairId = std::pair<size_t, size_t> protected
Definition at line 66 of file simd_collision_error_function.h.
Constructor & Destructor Documentation
SimdCollisionErrorFunctionT() [1/2]
template<typename T > momentum::SimdCollisionErrorFunctionT< T >::SimdCollisionErrorFunctionT (const Skeleton & skel, const ParameterTransform & pt, const CollisionGeometry & collisionGeometry) explicit
Definition at line 83 of file simd_collision_error_function.cpp.
References momentum::SimdCollisionErrorFunctionT< T >::updateCollisionPairs().
SimdCollisionErrorFunctionT() [2/2]
template<typename T > momentum::SimdCollisionErrorFunctionT< T >::SimdCollisionErrorFunctionT (const Character & character) explicit
Definition at line 92 of file simd_collision_error_function.cpp.
Member Function Documentation
computeBroadPhase()
template<typename T > void momentum::SimdCollisionErrorFunctionT< T >::computeBroadPhase (const SkeletonStateT< T > & state) protected
Definition at line 193 of file simd_collision_error_function.cpp.
References MT_PROFILE_EVENT, and momentum::updateAabb().
getError()
template<typename T > double momentum::SimdCollisionErrorFunctionT< T >::getError (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > &) final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 235 of file simd_collision_error_function.cpp.
References distance, momentum::kParametersPerJoint, and MT_CHECK.
getGradient()
template<typename T > double momentum::SimdCollisionErrorFunctionT< T >::getGradient (const ModelParametersT< T > & params, const SkeletonStateT< T > & state, const MeshStateT< T > & , Ref< VectorX< T > > gradient) override
Definition at line 284 of file simd_collision_error_function.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, momentum::kSimdPacketSize, and MT_CHECK.
getJacobian()
template<typename T > double momentum::SimdCollisionErrorFunctionT< T >::getJacobian (const ModelParametersT< T > & , const SkeletonStateT< T > & state, const MeshStateT< T > & , Ref< MatrixX< T > > jacobian, Ref< VectorX< T > > residual, int & usedRows) override
Definition at line 477 of file simd_collision_error_function.cpp.
References distance, momentum::kInvalidIndex, momentum::kParametersPerJoint, and momentum::kSimdPacketSize.
getJacobianSize()
template<typename T > size_t momentum::SimdCollisionErrorFunctionT< T >::getJacobianSize () const final virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 669 of file simd_collision_error_function.cpp.
updateCollisionPairs()
template<typename T > void momentum::SimdCollisionErrorFunctionT< T >::updateCollisionPairs () protected
Definition at line 104 of file simd_collision_error_function.cpp.
References distance, momentum::overlaps(), and momentum::updateAabb().
Referenced by momentum::SimdCollisionErrorFunctionT< T >::SimdCollisionErrorFunctionT().
Member Data Documentation
bvh_
template<typename T > axel::Bvh<T> momentum::SimdCollisionErrorFunctionT< T >::bvh_ protected
Definition at line 96 of file simd_collision_error_function.h.
collisionGeometry_
template<typename T > const CollisionGeometry momentum::SimdCollisionErrorFunctionT< T >::collisionGeometry_ protected
Definition at line 83 of file simd_collision_error_function.h.
collisionPairs_
template<typename T > std::vector<std::vector<int, AlignedAllocator<int, momentum::kSimdAlignment> > > momentum::SimdCollisionErrorFunctionT< T >::collisionPairs_ protected
Definition at line 87 of file simd_collision_error_function.h.
collisionState_
template<typename T > CollisionGeometryStateT<T> momentum::SimdCollisionErrorFunctionT< T >::collisionState_ protected
Definition at line 91 of file simd_collision_error_function.h.
excludingPairIds_
template<typename T > std::unordered_set<PairId, PairHash, PairEqual> momentum::SimdCollisionErrorFunctionT< T >::excludingPairIds_ protected
Definition at line 85 of file simd_collision_error_function.h.
jacobianSize_
template<typename T > size_t momentum::SimdCollisionErrorFunctionT< T >::jacobianSize_ = 0 protected
Definition at line 89 of file simd_collision_error_function.h.
kCollisionWeight
template<typename T > constexpr T momentum::SimdCollisionErrorFunctionT< T >::kCollisionWeight = 5e-3f static constexpr protected
Definition at line 94 of file simd_collision_error_function.h.
The documentation for this class was generated from the following files:
character_solver/fwd.h
character_solver/simd_collision_error_function.h
character_solver/simd_collision_error_function.cpp