Momentum: momentum::SimdNormalErrorFunction Class Reference
momentum::SimdNormalErrorFunction Class Reference
A highly optimized error function for "point-to-plane" (signed) distance errors.
#include <simd_normal_error_function.h>
Public Member Functions
SimdNormalErrorFunction (const Skeleton &skel, const ParameterTransform &pt, uint32_t maxThreads=std::numeric_limits< uint32_t >::max())
SimdNormalErrorFunction (const Character &character, uint32_t maxThreads=std::numeric_limits< uint32_t >::max())
double getError (const ModelParameters &params, const SkeletonState &state, const MeshState &meshState) final
double getGradient (const ModelParameters &params, const SkeletonState &state, const MeshState &meshState, Ref< VectorXf > gradient) final
double getJacobian (const ModelParameters &params, const SkeletonState &state, const MeshState &meshState, Ref< MatrixXf > jacobian, Ref< VectorXf > residual, int &usedRows) override
size_t getJacobianSize () const override
void setConstraints (const SimdNormalConstraints *cstrs)
Public Member Functions inherited from momentum::SkeletonErrorFunctionT< T >
SkeletonErrorFunctionT (const Skeleton &skel, const ParameterTransform &pt)
virtual ~SkeletonErrorFunctionT ()=default
const Skeleton & getSkeleton () const
const ParameterTransform & getParameterTransform () const
virtual const Character * getCharacter () const
For mesh-based error functions, get access to the underlying character.
void setWeight (T w)
T getWeight () const
void setActiveJoints (const VectorX< bool > &aj)
void setEnabledParameters (const ParameterSet &ps)
virtual double getError (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &)
virtual double getGradient (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::VectorX< T > >)
virtual double getJacobian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >, Eigen::Ref< Eigen::VectorX< T > >, int &usedRows)
virtual void getHessian (const ModelParametersT< T > &, const SkeletonStateT< T > &, const MeshStateT< T > &, Eigen::Ref< Eigen::MatrixX< T > >)
virtual double getSolverDerivatives (const ModelParametersT< T > &parameters, const SkeletonStateT< T > &state, const MeshStateT< T > &meshState, const size_t actualParameters, Eigen::MatrixX< T > &hess, Eigen::VectorX< T > &grad)
virtual bool needsMesh () const
Protected Attributes
std::vector< size_t > jacobianOffset_
const SimdNormalConstraints * constraints_
uint32_t maxThreads_
Protected Attributes inherited from momentum::SkeletonErrorFunctionT< T >
const Skeleton & skeleton_
const ParameterTransform & parameterTransform_
T weight_
VectorX< bool > activeJointParams_
ParameterSet enabledParameters_
bool useHessian_ {false}
Static Protected Attributes
static constexpr float kPlaneWeight = 1e-4f
Detailed Description
A highly optimized error function for "point-to-plane" (signed) distance errors.
See NormalErrorFunction for detailed explanation.
This function should primarily be used when dealing with a large number of constraints. For smaller numbers of constraints, consider using the generic NormalErrorFunction.
Warning
Due to the multi-threaded evaluation of the error/gradient, the functions are non-deterministic, which may cause numerical inconsistencies. As a result, slightly different results may occur on multiple calls with the same data.
Definition at line 71 of file simd_normal_error_function.h.
Constructor & Destructor Documentation
SimdNormalErrorFunction() [1/2]
momentum::SimdNormalErrorFunction::SimdNormalErrorFunction (const Skeleton & skel, const ParameterTransform & pt, uint32_t maxThreads = std::numeric_limits<uint32_t>::max()) explicit
Parameters
maxThreads An optional parameter that specifies the maximum number of threads to be used with dispenso::parallel_for. If this parameter is set to zero, the function will run in serial mode, i.e., it will not use any additional threads. By default, the value is set to the maximum allowable size of a uint32_t, which is also the default for dispenso.
Definition at line 107 of file simd_normal_error_function.cpp.
References constraints_.
SimdNormalErrorFunction() [2/2]
momentum::SimdNormalErrorFunction::SimdNormalErrorFunction (const Character & character, uint32_t maxThreads = std::numeric_limits<uint32_t>::max()) explicit
Parameters
maxThreads An optional parameter that specifies the maximum number of threads to be used with dispenso::parallel_for. If this parameter is set to zero, the function will run in serial mode, i.e., it will not use any additional threads. By default, the value is set to the maximum allowable size of a uint32_t, which is also the default for dispenso.
Definition at line 115 of file simd_normal_error_function.cpp.
Member Function Documentation
getError()
double momentum::SimdNormalErrorFunction::getError (const ModelParameters & params, const SkeletonState & state, const MeshState & meshState) final
Definition at line 118 of file simd_normal_error_function.cpp.
References momentum::SimdNormalConstraints::constraintCount, constraints_, momentum::dot(), momentum::SimdNormalConstraints::kMaxConstraints, kPlaneWeight, momentum::kSimdPacketSize, MT_CHECK, momentum::normal(), momentum::SimdNormalConstraints::normalX, momentum::SimdNormalConstraints::normalY, momentum::SimdNormalConstraints::normalZ, momentum::SimdNormalConstraints::numJoints, momentum::SimdNormalConstraints::offsetX, momentum::SimdNormalConstraints::offsetY, momentum::SimdNormalConstraints::offsetZ, momentum::operator*(), momentum::SimdNormalConstraints::targetX, momentum::SimdNormalConstraints::targetY, momentum::SimdNormalConstraints::targetZ, momentum::SkeletonErrorFunctionT< T >::weight_, and momentum::SimdNormalConstraints::weights.
getGradient()
double momentum::SimdNormalErrorFunction::getGradient (const ModelParameters & params, const SkeletonState & state, const MeshState & meshState, Ref< VectorXf > gradient) final
Definition at line 166 of file simd_normal_error_function.cpp.
References momentum::SkeletonErrorFunctionT< T >::activeJointParams_, momentum::SimdNormalConstraints::constraintCount, constraints_, momentum::cross(), momentum::dot(), momentum::SkeletonT< T >::joints, momentum::kInvalidIndex, momentum::SimdNormalConstraints::kMaxConstraints, momentum::kParametersPerJoint, kPlaneWeight, momentum::kSimdPacketSize, momentum::ln2(), momentum::normal(), momentum::SimdNormalConstraints::normalX, momentum::SimdNormalConstraints::normalY, momentum::SimdNormalConstraints::normalZ, momentum::SimdNormalConstraints::numJoints, momentum::SimdNormalConstraints::offsetX, momentum::SimdNormalConstraints::offsetY, momentum::SimdNormalConstraints::offsetZ, momentum::operator*(), momentum::operator-(), momentum::SkeletonErrorFunctionT< T >::parameterTransform_, momentum::SkeletonErrorFunctionT< T >::skeleton_, momentum::SimdNormalConstraints::targetX, momentum::SimdNormalConstraints::targetY, momentum::SimdNormalConstraints::targetZ, momentum::ParameterTransformT< T >::transform, momentum::SkeletonErrorFunctionT< T >::weight_, and momentum::SimdNormalConstraints::weights.
getJacobian()
double momentum::SimdNormalErrorFunction::getJacobian (const ModelParameters & params, const SkeletonState & state, const MeshState & meshState, Ref< MatrixXf > jacobian, Ref< VectorXf > residual, int & usedRows) override
Definition at line 288 of file simd_normal_error_function.cpp.
References constraints_, jacobianOffset_, maxThreads_, MT_CHECK, MT_PROFILE_FUNCTION, momentum::SimdNormalConstraints::numJoints, momentum::SkeletonErrorFunctionT< T >::parameterTransform_, and momentum::ParameterTransformT< T >::transform.
getJacobianSize()
size_t momentum::SimdNormalErrorFunction::getJacobianSize () const override virtual
Reimplemented from momentum::SkeletonErrorFunctionT< T >.
Definition at line 410 of file simd_normal_error_function.cpp.
References momentum::kSimdPacketSize.
setConstraints()
void momentum::SimdNormalErrorFunction::setConstraints (const SimdNormalConstraints * cstrs) inline
Definition at line 111 of file simd_normal_error_function.h.
References constraints_.
Member Data Documentation
constraints_
const SimdNormalConstraints* momentum::SimdNormalErrorFunction::constraints_ protected
Definition at line 122 of file simd_normal_error_function.h.
Referenced by getError(), getGradient(), getJacobian(), setConstraints(), and SimdNormalErrorFunction().
jacobianOffset_
std::vector<size_t> momentum::SimdNormalErrorFunction::jacobianOffset_ mutable protected
Definition at line 119 of file simd_normal_error_function.h.
Referenced by getJacobian().
kPlaneWeight
constexpr float momentum::SimdNormalErrorFunction::kPlaneWeight = 1e-4f static constexpr protected
Definition at line 117 of file simd_normal_error_function.h.
Referenced by getError(), and getGradient().
maxThreads_
uint32_t momentum::SimdNormalErrorFunction::maxThreads_ protected
Definition at line 124 of file simd_normal_error_function.h.
Referenced by getJacobian().
The documentation for this class was generated from the following files:
character_solver/simd_normal_error_function.h
character_solver/simd_normal_error_function.cpp