Momentum: momentum::BlendShape Struct Reference
momentum::BlendShape Struct Reference
Skinning class that combines blend shape vectors with a base shape.
#include <blend_shape.h>
Public Member Functions
BlendShape ()
BlendShape (std::span< const Vector3f > baseShape, size_t numShapes, std::span< const std::string > shapeNames={})
void setBaseShape (std::span< const Vector3f > baseShape)
const std::vector< Vector3f > & getBaseShape () const
bool getFactorizationValid () const
Whether SVD factorization is up-to-date.
template<typename T >
std::vector< Eigen::Vector3< T > > computeShape (const BlendWeightsT< T > &coefficients) const
Applies blend weights to create a deformed shape.
template<typename T >
void computeShape (const BlendWeightsT< T > &coefficients, std::vector< Eigen::Vector3< T > > &result) const
Output parameter version of computeShape.
VectorXf estimateCoefficients (std::span< const Vector3f > vertices, float regularization=1.0f, const VectorXf &weights=VectorXf()) const
Solves for blend weights that best approximate a target shape.
void setShapeVector (size_t index, std::span< const Vector3f > shapeVector, std::string_view name="")
Overrides base method to also invalidate factorization.
bool isApprox (const BlendShape &blendShape) const
Compares all components of two blend shapes.
Public Member Functions inherited from momentum::BlendShapeBase
BlendShapeBase ()=default
BlendShapeBase (size_t modelSize, size_t numShapes, std::span< const std::string > shapeNames={})
virtual ~BlendShapeBase ()=default
void setShapeVectors (const MatrixXf &shapeVectors, std::span< const std::string > shapeNames={})
const MatrixXf & getShapeVectors () const
template<typename T >
VectorX< T > computeDeltas (const BlendWeightsT< T > &blendWeights) const
Calculates weighted combination of shape vectors.
template<typename T >
void applyDeltas (const BlendWeightsT< T > &blendWeights, std::vector< Eigen::Vector3< T > > &result) const
Adds weighted shape vectors to existing vertices.
void setShapeVector (size_t index, std::span< const Vector3f > shapeVector, std::string_view name="")
Eigen::Index shapeSize () const
size_t modelSize () const
Returns number of vertices (rows/3)
const std::vector< std::string > & getShapeNames () const
std::string_view getShapeName (size_t index) const
void setShapeName (size_t index, std::string_view name)
Additional Inherited Members
Protected Attributes inherited from momentum::BlendShapeBase
MatrixXf shapeVectors_
std::vector< std::string > shapeNames_
Detailed Description
Skinning class that combines blend shape vectors with a base shape.
Extends BlendShapeBase by adding a base shape (e.g., PCA mean) and functionality for computing deformed shapes and estimating blend coefficients. Primarily used to model identity-dependent shape deformations.
Definition at line 19 of file blend_shape.h.
Constructor & Destructor Documentation
BlendShape() [1/2]
momentum::BlendShape::BlendShape () inline
Definition at line 21 of file blend_shape.h.
BlendShape() [2/2]
momentum::BlendShape::BlendShape (std::span< const Vector3f > baseShape, size_t numShapes, std::span< const std::string > shapeNames = {})
Parameters
baseShape Base shape vertices
numShapes Number of blend shapes
shapeNames Names of the blend shapes (will be automatically generated if empty or not the right size)
Definition at line 91 of file blend_shape.cpp.
Member Function Documentation
computeShape() [1/2]
template<typename T > std::vector< Eigen::Vector3< T > > momentum::BlendShape::computeShape (const BlendWeightsT< T > & coefficients) const
Applies blend weights to create a deformed shape.
Adds weighted shape vectors to the base shape
Template Parameters
T Scalar type (float or double)
Parameters
coefficients Weights for each shape vector
Returns
Resulting deformed shape
Definition at line 17 of file blend_shape.cpp.
References computeShape().
Referenced by computeShape().
computeShape() [2/2]
template<typename T > void momentum::BlendShape::computeShape (const BlendWeightsT< T > & coefficients, std::vector< Eigen::Vector3< T > > & result) const
Output parameter version of computeShape.
Template Parameters
T Scalar type (float or double)
Parameters
coefficients Weights for each shape vector
result [out] Resulting deformed shape
Definition at line 25 of file blend_shape.cpp.
References MT_CHECK, and momentum::BlendShapeBase::shapeVectors_.
estimateCoefficients()
VectorXf momentum::BlendShape::estimateCoefficients (std::span< const Vector3f > vertices, float regularization = 1.0f, const VectorXf & weights = VectorXf()) const
Solves for blend weights that best approximate a target shape.
Uses SVD to find optimal coefficients with optional regularization and per-vertex weighting
Parameters
vertices Target shape to approximate
regularization Higher values produce smaller coefficients
weights Optional per-vertex importance weights
Returns
Estimated blend shape coefficients
Definition at line 41 of file blend_shape.cpp.
References MT_CHECK, and momentum::BlendShapeBase::shapeVectors_.
getBaseShape()
const std::vector< Vector3f > & momentum::BlendShape::getBaseShape () const inline
Definition at line 36 of file blend_shape.h.
Referenced by isApprox(), and momentum::saveBlendShape().
getFactorizationValid()
bool momentum::BlendShape::getFactorizationValid () const inline
Whether SVD factorization is up-to-date.
Definition at line 41 of file blend_shape.h.
Referenced by isApprox().
isApprox()
bool momentum::BlendShape::isApprox (const BlendShape & blendShape) const
Compares all components of two blend shapes.
Parameters
blendShape Other blend shape to compare with
Definition at line 109 of file blend_shape.cpp.
References getBaseShape(), getFactorizationValid(), momentum::BlendShapeBase::getShapeVectors(), isApprox(), and momentum::BlendShapeBase::shapeVectors_.
Referenced by isApprox().
setBaseShape()
void momentum::BlendShape::setBaseShape (std::span< const Vector3f > baseShape) inline
Definition at line 32 of file blend_shape.h.
setShapeVector()
void momentum::BlendShape::setShapeVector (size_t index, std::span< const Vector3f > shapeVector, std::string_view name = "")
Overrides base method to also invalidate factorization.
Parameters
index Index of the shape vector to set
shapeVector Vector of vertex offsets
Definition at line 99 of file blend_shape.cpp.
References momentum::BlendShapeBase::setShapeVector().
The documentation for this struct was generated from the following files:
character/blend_shape.h
character/blend_shape.cpp