Momentum: momentum::SkeletonStateT< T > Struct Template Reference
momentum::SkeletonStateT< T > Struct Template Reference
Represents the complete state of a skeleton.
#include <skeleton_state.h>
Public Member Functions
SkeletonStateT () noexcept=default
Creates an empty skeleton state.
SkeletonStateT (const JointParametersT< T > &parameters, const Skeleton &referenceSkeleton, bool computeDeriv=true)
Creates a skeleton state from joint parameters and a reference skeleton.
SkeletonStateT (JointParametersT< T > &&parameters, const Skeleton &referenceSkeleton, bool computeDeriv=true)
Creates a skeleton state from rvalue joint parameters and a reference skeleton.
template<typename T2 >
SkeletonStateT (const SkeletonStateT< T2 > &rhs)
Creates a skeleton state from another skeleton state with a different scalar type.
void set (const JointParametersT< T > &jointParameters, const Skeleton &referenceSkeleton, bool computeDeriv=true)
Updates the skeleton state with new joint parameters.
void set (JointParametersT< T > &&jointParameters, const Skeleton &referenceSkeleton, bool computeDeriv=true)
Updates the skeleton state with new rvalue joint parameters.
template<typename T2 >
void set (const SkeletonStateT< T2 > &rhs)
Updates the skeleton state from another skeleton state with a different scalar type.
TransformListT< T > toTransforms () const
Extracts global transforms for all joints in the skeleton.
template<typename T2 >
SkeletonStateT< T2 > cast () const
Converts the skeleton state to a different scalar type.
Static Public Member Functions
static StateSimilarity compare (const SkeletonStateT< T > &state1, const SkeletonStateT< T > &state2)
Compares two skeleton states and returns similarity metrics.
Public Attributes
JointParametersT< T > jointParameters
Joint parameters for all joints in the skeleton.
JointStateListT< T > jointState
Computed joint states for all joints in the skeleton.
Detailed Description
template<typename T>
struct momentum::SkeletonStateT< T >
Represents the complete state of a skeleton.
Stores joint parameters and computed joint states for an entire skeleton. Provides methods for updating the state based on new parameters and comparing different skeleton states.
Definition at line 45 of file skeleton_state.h.
Constructor & Destructor Documentation
SkeletonStateT() [1/4]
template<typename T > momentum::SkeletonStateT< T >::SkeletonStateT () default noexcept
Creates an empty skeleton state.
SkeletonStateT() [2/4]
template<typename T > momentum::SkeletonStateT< T >::SkeletonStateT (const JointParametersT< T > & parameters, const Skeleton & referenceSkeleton, bool computeDeriv = true)
Creates a skeleton state from joint parameters and a reference skeleton.
Parameters
parameters Joint parameters for all joints in the skeleton
referenceSkeleton The skeleton structure defining joint hierarchy
computeDeriv Whether to compute derivative information for the joints
Definition at line 22 of file skeleton_state.cpp.
References momentum::SkeletonStateT< T >::set().
SkeletonStateT() [3/4]
template<typename T > momentum::SkeletonStateT< T >::SkeletonStateT (JointParametersT< T > && parameters, const Skeleton & referenceSkeleton, bool computeDeriv = true)
Creates a skeleton state from rvalue joint parameters and a reference skeleton.
Parameters
parameters Joint parameters for all joints in the skeleton (moved from)
referenceSkeleton The skeleton structure defining joint hierarchy
computeDeriv Whether to compute derivative information for the joints
Definition at line 31 of file skeleton_state.cpp.
References momentum::SkeletonStateT< T >::set().
SkeletonStateT() [4/4]
template<typename T > template<typename T2 > momentum::SkeletonStateT< T >::SkeletonStateT (const SkeletonStateT< T2 > & rhs) explicit
Creates a skeleton state from another skeleton state with a different scalar type.
Template Parameters
T2 Source scalar type
Parameters
rhs Source skeleton state to copy from
Definition at line 41 of file skeleton_state.cpp.
Member Function Documentation
cast()
template<typename T > template<typename T2 > SkeletonStateT< T2 > momentum::SkeletonStateT< T >::cast () const inline
Converts the skeleton state to a different scalar type.
Template Parameters
T2 Target scalar type
Returns
Skeleton state with the target scalar type
Definition at line 128 of file skeleton_state.h.
References momentum::SkeletonStateT< T >::set().
compare()
template<typename T > StateSimilarity momentum::SkeletonStateT< T >::compare (const SkeletonStateT< T > & state1, const SkeletonStateT< T > & state2) static
Compares two skeleton states and returns similarity metrics.
Parameters
state1 First skeleton state to compare
state2 Second skeleton state to compare
Returns
Similarity metrics between the two states
Definition at line 141 of file skeleton_state.cpp.
References momentum::dot(), MT_CHECK, momentum::StateSimilarity::orientationError, momentum::StateSimilarity::orientationMax, momentum::StateSimilarity::orientationRMSE, momentum::StateSimilarity::positionError, momentum::StateSimilarity::positionMax, and momentum::StateSimilarity::positionRMSE.
set() [1/3]
template<typename T > void momentum::SkeletonStateT< T >::set (const JointParametersT< T > & jointParameters, const Skeleton & referenceSkeleton, bool computeDeriv = true)
Updates the skeleton state with new joint parameters.
Parameters
jointParameters New joint parameters for all joints
referenceSkeleton The skeleton structure defining joint hierarchy
computeDeriv Whether to compute derivative information for the joints
Definition at line 65 of file skeleton_state.cpp.
References MT_PROFILE_FUNCTION.
Referenced by momentum::SkeletonStateT< T >::cast(), momentum::getLocatorError(), momentum::sampleFrames(), momentum::SkeletonStateT< T >::SkeletonStateT(), and momentum::SkeletonStateT< T >::SkeletonStateT().
set() [2/3]
template<typename T > template<typename T2 > void momentum::SkeletonStateT< T >::set (const SkeletonStateT< T2 > & rhs)
Updates the skeleton state from another skeleton state with a different scalar type.
Template Parameters
T2 Source scalar type
Parameters
rhs Source skeleton state to copy from
Definition at line 48 of file skeleton_state.cpp.
References MT_PROFILE_FUNCTION.
set() [3/3]
template<typename T > void momentum::SkeletonStateT< T >::set (JointParametersT< T > && jointParameters, const Skeleton & referenceSkeleton, bool computeDeriv = true)
Updates the skeleton state with new rvalue joint parameters.
Parameters
jointParameters New joint parameters for all joints (moved from)
referenceSkeleton The skeleton structure defining joint hierarchy
computeDeriv Whether to compute derivative information for the joints
Definition at line 76 of file skeleton_state.cpp.
toTransforms()
template<typename T > TransformListT< T > momentum::SkeletonStateT< T >::toTransforms () const
Extracts global transforms for all joints in the skeleton.
Returns
List of global transforms for all joints
Definition at line 131 of file skeleton_state.cpp.
Referenced by momentum::StateErrorFunctionT< T >::setTargetState().
Member Data Documentation
jointParameters
template<typename T > JointParametersT<T> momentum::SkeletonStateT< T >::jointParameters
Joint parameters for all joints in the skeleton.
Definition at line 47 of file skeleton_state.h.
jointState
template<typename T > JointStateListT<T> momentum::SkeletonStateT< T >::jointState
Computed joint states for all joints in the skeleton.
Definition at line 50 of file skeleton_state.h.
Referenced by momentum::extractMarkersFromMotion(), momentum::DistanceErrorFunctionT< T >::getError(), momentum::ProjectionErrorFunctionT< T >::getError(), momentum::DistanceErrorFunctionT< T >::getGradient(), momentum::ProjectionErrorFunctionT< T >::getGradient(), momentum::DistanceErrorFunctionT< T >::getJacobian(), momentum::ProjectionErrorFunctionT< T >::getJacobian(), momentum::logCollisionGeometry(), momentum::StateErrorFunctionT< T >::setTargetState(), momentum::CollisionGeometryStateT< T >::update(), and momentum::PositionConstraintStateT< T >::update().
The documentation for this struct was generated from the following files:
character/fwd.h
character/skeleton_state.h
character/skeleton_state.cpp