Momentum: marker_tracking/tracker_utils.cpp File Reference
tracker_utils.cpp File Reference
#include "momentum/marker_tracking/tracker_utils.h"
#include "momentum/character/blend_shape.h"
#include "momentum/character/blend_shape_skinning.h"
#include "momentum/character/character.h"
#include "momentum/character/inverse_parameter_transform.h"
#include "momentum/character/parameter_limits.h"
#include "momentum/character/skeleton_state.h"
#include "momentum/character_solver/position_error_function.h"
#include "momentum/character_solver/skinned_locator_error_function.h"
#include "momentum/math/mesh.h"
#include "momentum/math/utility.h"
#include "momentum/common/log.h"
#include "axel/math/PointTriangleProjectionDefinitions.h"
Namespaces
namespace momentum
Functions
std::vector< std::vector< PositionData > > momentum::createConstraintData (const std::span< const std::vector< Marker > > markerData, const LocatorList &locators)
std::vector< std::vector< SkinnedLocatorConstraint > > momentum::createSkinnedConstraintData (const std::span< const std::vector< Marker > > markerData, const SkinnedLocatorList &locators)
std::pair< Eigen::Vector< uint32_t, kMaxSkinJoints >, Eigen::Vector< float, kMaxSkinJoints > > momentum::averageTriangleSkinWeights (const Character &character, int triangleIndex, const Eigen::Vector3f &barycentric)
ClosestPointOnMeshResult momentum::closestPointOnMeshMatchingParent (const momentum::Mesh &mesh, const momentum::SkinWeights &skin, const Eigen::Vector3f &p_world, uint32_t parentIdx, float cutoffWeight=0.1)
momentum::Character momentum::locatorsToSkinnedLocators (const momentum::Character &sourceCharacter, float maxDistance=3.0f)
Convert locators to skinned locators by finding the closest point on the mesh surface that matches the correct bone index and using the skinned weights from that point.
momentum::Character momentum::skinnedLocatorsToLocators (const momentum::Character &sourceCharacter)
Convert skinned locators to regular locators by selecting the bone with the highest skin weight.
std::vector< momentum::SkinnedLocatorTriangleConstraintT< float > > momentum::createSkinnedLocatorMeshConstraints (const momentum::Character &character, float targetDepth)
Character momentum::createLocatorCharacter (const Character &sourceCharacter, const std::string &prefix)
LocatorList momentum::extractLocatorsFromCharacter (const Character &locatorCharacter, const CharacterParameters &calibParams)
SkinnedLocatorList momentum::extractSkinnedLocatorsFromCharacter (const Character &locatorCharacter, const CharacterParameters &calibParams)
ModelParameters momentum::extractParameters (const ModelParameters &params, const ParameterSet &parameterSet)
std::tuple< Eigen::VectorXf, LocatorList, SkinnedLocatorList > momentum::extractIdAndLocatorsFromParams (const ModelParameters &param, const Character &sourceCharacter, const Character &targetCharacter)
Mesh momentum::extractBlendShapeFromParams (const momentum::ModelParameters &param, const momentum::Character &sourceCharacter)
void momentum::fillIdentity (const ParameterSet &idSet, const ModelParameters &identity, Eigen::MatrixXf &motionNoId)
void momentum::removeIdentity (const ParameterSet &idSet, const ModelParameters &identity, Eigen::MatrixXf &motionWithId)
ModelParameters momentum::jointIdentityToModelIdentity (const Character &c, const ParameterSet &idSet, const JointParameters &jointIdentity)
std::vector< std::vector< Marker > > momentum::extractMarkersFromMotion (const Character &character, const Eigen::MatrixXf &motion)
Variable Documentation
baryCoords
Eigen::Vector3f baryCoords = Eigen::Vector3f::Zero()
Definition at line 147 of file tracker_utils.cpp.
distance
float distance = std::numeric_limits<float>::max()
Definition at line 148 of file tracker_utils.cpp.
Referenced by momentum::closestPointsOnSegments(), momentum::CollisionErrorFunctionT< T >::getCollisionPairs(), momentum::SimdCollisionErrorFunctionT< T >::getError(), momentum::CollisionErrorFunctionT< T >::getError(), momentum::CollisionErrorFunctionStatelessT< T >::getError(), momentum::DistanceErrorFunctionT< T >::getError(), momentum::SimdCollisionErrorFunctionT< T >::getGradient(), momentum::CollisionErrorFunctionT< T >::getGradient(), momentum::CollisionErrorFunctionStatelessT< T >::getGradient(), momentum::DistanceErrorFunctionT< T >::getGradient(), momentum::SimdCollisionErrorFunctionT< T >::getJacobian(), momentum::CollisionErrorFunctionT< T >::getJacobian(), momentum::CollisionErrorFunctionStatelessT< T >::getJacobian(), momentum::DistanceErrorFunctionT< T >::getJacobian(), momentum::CollisionErrorFunctionT< T >::updateCollisionPairs(), momentum::CollisionErrorFunctionStatelessT< T >::updateCollisionPairs(), and momentum::SimdCollisionErrorFunctionT< T >::updateCollisionPairs().
triangleIdx
size_t triangleIdx = kInvalidIndex
Definition at line 146 of file tracker_utils.cpp.
valid
bool valid = false
Definition at line 145 of file tracker_utils.cpp.